project:
  type: website
  render:
    - index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly

website:
  title: "ProjectX"
  navbar:
    left:
      - text: Blog
        href: "#"
      - text: Help
        href: "#"
    tools:
      - icon: bluesky
        href: https://bsky.app
      - icon: github
        menu:
          - text: Source Code
            href: https://code.com
          - text: Report a Bug
            href: https://bugs.com
