---
title: "Frequently Asked Questions"
editor: source
---

FIXME: testing actions

If you are an R Markdown user wondering about the relationship between Quarto and R Markdown, see also our [FAQ for R Markdown Users](rmarkdown.qmd).

## General

### What can I use Quarto for?

Quarto® is an open-source scientific and technical publishing system built on Pandoc. You can weave together narrative text and code to produce elegantly formatted output as documents, web pages, blog posts, books and more.

### How do I install Quarto?

Visit the [Quarto.org - Get Started page](/docs/get-started/index.qmd), which provides installation instructions for Windows, Mac OS, and Linux.

### What output formats can Quarto create?

There are many output formats available in Quarto. This includes all of the built in Pandoc formats (e.g. HTML, PDF, MS Word, Revealjs, ePub, etc.) as well as various ways to publish multiple documents (websites, blogs, and books). Learn more at [Quarto Formats](/docs/output-formats/all-formats.qmd).

### What editing tools can I use with Quarto?

You can use a wide variety of tools with Quarto. We have provided documentation for writing and editing Quarto documents in VSCode, JupyterLab, RStudio IDE, or any text editor. Visit the [Get Started with Quarto page](/docs/get-started/index.qmd) to install, and then choose your tool for a brief introductory guide.

### Can I use Jupyter notebooks with Quarto?

Yes! Quarto can [render Jupyter notebooks](/docs/tools/jupyter-lab.qmd) and you can use Jupyter, JupyterLab or any other .ipynb notebook editor with Quarto. You can render existing .ipynb notebooks as-is with Quarto, but adding Quarto-specific output options or a YAML header can enhance the output. Visit the[JupyterLab page](/docs/tools/jupyter-lab.qmd) for more information.

### What programming languages are supported in Quarto?

The principal languages supported by Quarto are Python, R, Julia, and Observable JavaScript. Integration with Jupyter also enables the use of many other languages. 

Each Quarto document can be optionally processed by a computational engine (the engine can be manually specified or automatically detected based on the code chunks within). Current engines include Knitr (which is also used by R Markdown and supports [a variety of languages](https://bookdown.org/yihui/rmarkdown-cookbook/other-languages.html) including R, Python, and Julia, etc.) and Jupyter (which supports many languages including Python, Julia, and R). See the documentation on [Engine Binding](/docs/computations/execution-options.qmd#engine-binding) for additional details.

### What human languages are supported in Quarto?

You can write your Quarto documentation in your human language of choice. The [lang](https://pandoc.org/MANUAL.html#language-variables) [document option](/docs/authoring/language.qmd#lang-option) is used to identify the main language of the document using IETF language tags (following the [BCP 47 standard](https://tools.ietf.org/html/bcp47)), such as en or en-GB. 

### Where can I report bugs or request features?

Thanks for finding something and sharing with us! You can file an issue in the Quarto repository <https://github.com/quarto-dev/quarto-cli/issues>.

### Where can I ask questions and discuss using Quarto with others?

The best place to ask questions and see what questions other people have is in Quarto discussions (<https://github.com/quarto-dev/quarto-cli/discussions>). 

## Development and Maintenance

### How can I upgrade dependencies?

Generally, you cannot.
Quarto produces output tailored to its downstream dependencies (Pandoc, `typst`, etc), and uses features that depend on specific upstream dependencies (Deno).
Our installers bundle all required dependencies to eliminate version mismatch risks, and we *strongly recommend* that third-party packagers
follow the same policy.

### How often are dependencies updated?

Ideally, we update dependencies exactly once every stable release (1.2, 1.3, etc).
We reserve the right to change the cadence as necessary for our development.

### What are Quarto's dependencies?

Quarto's dependencies include:

- [Pandoc](https://pandoc.org)
- [Typst](https://typst.app)
- [Deno](https://deno.com)
- [Mermaid](https://mermaid.js.org)
- [esbuild](https://esbuild.github.io/)
- [Dart Sass](https://sass-lang.com/dart-sass/)

## Licensing

### Is Quarto free to use?

Yes! Quarto is [open source](/license.md). Quarto version 1.3 (and earlier) is licensed under the [GNU GPL v2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html). Quarto version 1.4 is licensed under the [MIT License](https://opensource.org/license/mit/).

### Can I use Quarto to develop proprietary content?

Yes! The copyright on Quarto does not cover the original content that you generate using Quarto. Using Quarto to create original content does not place any restrictions, legally, on the license that you choose for the original content that you create, nor does it “reach through” to affect software that you might be writing documentation for with Quarto.

### But doesn't the GPL cover exported HTML documents when they include styles or functionalities from Quarto?

It covers the styles or functionalities themselves.  It does not cover your original content because your original content is not a derivative work of the Quarto styles or functionalities.

### How can I share documents and have people comment on them?

You can publish Quarto content to various locations. See the user guides for [publishing](/docs/publishing/index.qmd) for details on using Quarto Pub, GitHub Pages, Netlify, Posit Connect, and other services with Quarto. Once documents are published you can use  [hypothes.is](https://web.hypothes.is/), [Utterances](https://utteranc.es/), or [Giscus](https://giscus.app/) for commenting. Learn more in the documentation on [commenting](/docs/output-formats/html-basics.qmd#commenting).

### Can I do collaborative editing with Quarto?

There is not yet anything specific for collaborative editing in Quarto. You can collaborate on .qmd files in the same way you currently do for any text or code files. 

Posit Workbench allows for [Project Sharing](https://support.rstudio.com/hc/en-us/articles/211659737-Sharing-Projects-in-RStudio-Workbench-RStudio-Server-Pro) for interactive editing and collaboration on the same document.

### Where can I publish Quarto websites?

There are a wide variety of ways to publish Quarto websites. Website content is by default written to the `\_site` sub-directory (you can customize this using the output-dir option). Publishing is simply a matter of copying the output directory to a web server or web hosting service.

The [publishing documentation](/docs/publishing/other.qmd) describes several convenient options for Quarto website deployment including Posit Connect, Netlify, GitHub Pages, Firebase, Site44, and Amazon S3. We'll mostly defer to the documentation provided by those various services, but will note any Quarto website specific configuration required.

## Quarto + Posit

### Does Posit Connect support Quarto?

Yes! You can publish Quarto content to Posit Connect v2021.08.0 or later. Quarto has to be enabled as documented in the Posit Connect [admin guide](https://docs.rstudio.com/connect/admin/appendix/configuration/#Quarto). Connect's user [documentation](https://docs.rstudio.com/connect/user/quarto/) refers to [Quarto.org docs](/docs/publishing/index.qmd#rstudio-connect) on how to publish from the RStudio IDE. To publish Python-based Quarto content, you can use the [rsconnect-python CLI](https://docs.rstudio.com/rsconnect-python/) from various locations, including VSCode, JupyterLab or the terminal.

## Meta

### Who are the developers of Quarto?

Development of Quarto is sponsored by [Posit, PBC](https://www.posit.co/). The same core team works on both Quarto and R Markdown:

-   Carlos Scheidegger ([\@cscheid](https://github.com/cscheid))

-   Gordon Woodhull ([\@gordonwoodhull](https://github.com/gordonwoodhull))

-   Christophe Dervieux ([\@cderv](https://github.com/cderv))

-   Charles Teague ([\@dragonstyle](https://github.com/dragonstyle))

-   J.J. Allaire ([\@jjallaire](https://github.com/jjallaire/))

-   Yihui Xie ([\@yihui](https://github.com/yihui))

Here is the [full contributors list](https://github.com/quarto-dev/quarto-cli/graphs/contributors). Quarto is open source and we welcome contributions in our github repository as well! <https://github.com/quarto-dev/quarto-cli>.

### Why the name Quarto?

We wanted to use a name that had meaning in the history of publishing and landed on Quarto, which is the format of a book or pamphlet produced from full sheets printed with eight pages of text, four to a side, then folded twice to produce four leaves. The earliest known European printed book is a Quarto, the [Sibyllenbuch](https://en.wikipedia.org/wiki/Sibyllenbuch_fragment), believed to have been printed by [Johannes Gutenberg](https://en.wikipedia.org/wiki/Johannes_Gutenberg) in 1452--53.
