---
title: PDF Format Improvements
---

## SVG Images

Starting in Quarto 1.3, we support rendering of PDF documents that include SVG files, automatically converting them to PDF images if `rsvg-convert` is available on the system path during rendering.

You can learn more about installing `libsvg`{spellcheck="false"} (which provides `rsvg-convert`{spellcheck="false"}), see <https://wiki.gnome.org/Projects/LibRsvg>. To install on specific platforms, follow the below instructions:

-   On MacOS, you an use Homebrew (<https://formulae.brew.sh/formula/libsvg>) `brew install libsvg`{spellcheck="false"}

-   Tarballs for Linux are available here: <https://download.gnome.org/sources/librsvg/>

-   On Windows, you can install using chocolatey [https://community.chocolatey.org/packages/r...](https://community.chocolatey.org/packages/r…){.uri} `choco install rsvg-convert`{spellcheck="false"}

## Remote Images

Starting in Quarto 1.3, when rendering PDFs, Quarto will automatically fetch remote image references and properly embed them within the PDF.