--- Gitlink Repository Navbar Widget
--- @module "widget"
--- @license MIT
--- @copyright 2026 Mickaël Canouil
--- @author Mickaël Canouil
--- @brief Injects the repository navbar widget (live stars/forks counts and a
--- links dropdown) into HTML output from the `extensions.gitlink.widget`
--- configuration and the per-platform `widget` sections of platforms.yml.

local widget_module = {}

local str = require(quarto.utils.resolve_path('_vendor/quarto-lua-modules/string.lua'):gsub('%.lua$', ''))
local log = require(quarto.utils.resolve_path('_vendor/quarto-lua-modules/logging.lua'):gsub('%.lua$', ''))
local html_mod = require(quarto.utils.resolve_path('_vendor/quarto-lua-modules/html.lua'):gsub('%.lua$', ''))

--- @type string Version used for the injected HTML dependency
local WIDGET_DEPENDENCY_VERSION = '1.9.0'

--- @type table<string, string>|nil Octicon SVG bodies by name (loaded once per render)
local octicons_cache = nil

--- Load the embedded octicon set (octicons.json, generated by
--- tools/generate-octicons.py). Only the icons a page's menu actually uses
--- are embedded into the widget configuration, so the full set never reaches
--- the rendered page.
--- @param extension_name string The extension name (for warnings)
--- @return table<string, string> Octicon SVG bodies by name
local function load_octicons(extension_name)
  if octicons_cache then
    return octicons_cache
  end
  octicons_cache = {}
  local path = quarto.utils.resolve_path('octicons.json')
  local file = io.open(path, 'r')
  if not file then
    log.log_warning(
      extension_name,
      "Missing 'octicons.json': widget icons fall back to Bootstrap names only. " ..
      'Regenerate it with tools/generate-octicons.py.'
    )
    return octicons_cache
  end
  local content = file:read('*all')
  file:close()
  local ok, decoded = pcall(quarto.json.decode, content)
  if ok and type(decoded) == 'table' then
    octicons_cache = decoded
  else
    log.log_warning(
      extension_name,
      "Failed to parse 'octicons.json': widget icons fall back to Bootstrap names only."
    )
  end
  return octicons_cache
end

--- Coerce a metadata value to a boolean with a default.
--- @param value any The raw metadata value (boolean, MetaValue, or nil)
--- @param default boolean The default when the value is absent
--- @return boolean The resolved boolean
local function to_boolean(value, default)
  if value == nil then
    return default
  end
  if type(value) == 'boolean' then
    return value
  end
  return str.stringify(value):lower() == 'true'
end

--- Percent-encode a string for use as a URL path segment.
--- @param value string The value to encode
--- @return string The encoded value
local function url_encode(value)
  local encoded = value:gsub('[^%w%-%._~]', function(char)
    return string.format('%%%02X', string.byte(char))
  end)
  return encoded
end

--- Substitute `{repo}`, `{repo-encoded}`, `{base-url}`, and `{username}`
--- placeholders in a template. Function replacements keep literal `%` in the
--- substituted values from being interpreted as gsub captures.
--- @param template string The template string
--- @param context table Fields: repo, base_url, username (all optional)
--- @return string The resolved string
local function resolve_template(template, context)
  local resolved = template
  resolved = resolved:gsub('{repo%-encoded}', function() return url_encode(context.repo or '') end)
  resolved = resolved:gsub('{repo}', function() return context.repo or '' end)
  resolved = resolved:gsub('{base%-url}', function() return context.base_url or '' end)
  resolved = resolved:gsub('{username}', function() return context.username or '' end)
  return resolved
end

--- @type table<string, boolean> Elements allowed in structured label parts
local ALLOWED_LABEL_TAGS = {
  ['iconify-icon'] = true,
  span = true,
  em = true,
  strong = true,
  code = true,
  sub = true,
  sup = true,
  i = true,
}

--- @type table<string, boolean> Attributes allowed on label elements
local ALLOWED_LABEL_ATTRIBUTES = {
  class = true,
  icon = true,
  width = true,
  height = true,
  inline = true,
  title = true,
  role = true,
  ['aria-label'] = true,
  ['aria-hidden'] = true,
}

--- Extract allowlisted elements and text from a raw HTML fragment into label
--- parts. Elements outside the allowlist are dropped and their surrounding
--- text kept, so widget.js can rebuild the label with createElement and
--- setAttribute without ever parsing HTML in the browser.
--- @param html string The raw HTML fragment (e.g. shortcode output)
--- @param parts table<integer, table> The accumulating list of label parts
local function raw_html_to_parts(html, parts)
  local position = 1
  while true do
    local start_pos, end_pos, tag, attr_text = html:find('<([%w-]+)(.-)>', position)
    local before = html:sub(position, (start_pos or 0) - 1):gsub('<[^>]*>', '')
    if before ~= '' then
      table.insert(parts, { text = before })
    end
    if not start_pos then
      break
    end
    local tag_lower = tag:lower()
    if ALLOWED_LABEL_TAGS[tag_lower] then
      local attrs = {}
      for name, value in attr_text:gmatch('([%w-]+)%s*=%s*"([^"]*)"') do
        if ALLOWED_LABEL_ATTRIBUTES[name:lower()] then
          attrs[name:lower()] = value
        end
      end
      -- Valueless boolean attributes (e.g. iconify's `inline`).
      local remainder = attr_text:gsub('([%w-]+)%s*=%s*"[^"]*"', '')
      for name in remainder:gmatch('([%w-]+)') do
        if ALLOWED_LABEL_ATTRIBUTES[name:lower()] and attrs[name:lower()] == nil then
          attrs[name:lower()] = ''
        end
      end
      table.insert(parts, { tag = tag_lower, attrs = attrs })
    end
    position = end_pos + 1
  end
end

--- Convert a metadata value to a structured label: either a plain string or
--- a list of parts ({text} or {tag, attrs}) preserving allowlisted shortcode
--- output (e.g. an iconify icon in an extra-link's `text`).
--- @param value any The metadata value
--- @return string|table The label string or parts list
local function meta_to_label(value)
  if pandoc.utils.type(value) ~= 'Inlines' then
    return str.stringify(value)
  end
  local parts = {}
  local buffer = {}
  local function flush()
    if #buffer > 0 then
      table.insert(parts, { text = table.concat(buffer) })
      buffer = {}
    end
  end
  for _, inline in ipairs(value) do
    if inline.t == 'RawInline' and (inline.format == 'html' or inline.format == 'html5') then
      flush()
      raw_html_to_parts(inline.text, parts)
    elseif inline.t == 'Space' or inline.t == 'SoftBreak' then
      table.insert(buffer, ' ')
    else
      table.insert(buffer, str.stringify(inline))
    end
  end
  flush()
  return parts
end

--- Whether the widget is enabled in the metadata (default false).
--- @param widget_meta table|nil The `extensions.gitlink.widget` metadata sub-table
--- @return boolean True when the widget should be injected
function widget_module.is_enabled(widget_meta)
  if widget_meta == nil then
    return false
  end
  return to_boolean(widget_meta['enabled'], false)
end

--- Append a link entry to the list when its toggle is on and a path exists.
--- @param links table The accumulating list of link entries
--- @param toggles table|nil The `widget.links` metadata sub-table
--- @param key string The toggle key (kebab-case, as written in YAML)
--- @param default boolean Whether the link is included when the toggle is absent
--- @param entry table|nil The link entry ({label, href, icon}) or nil when unsupported
local function append_default_link(links, toggles, key, default, entry)
  if not entry then
    return
  end
  if to_boolean(toggles and toggles[key], default) then
    table.insert(links, entry)
  end
end

--- Build a default link entry from a platform widget path template.
--- @param paths table|nil The platform `widget.paths` table (snake_case keys)
--- @param key string The path key (snake_case)
--- @param label string The link label
--- @param icon string The octicon key
--- @param context table The template context (repo, base_url)
--- @return table|nil The link entry or nil when the platform has no such path
local function platform_link(paths, key, label, icon, context)
  local template = paths and paths[key]
  if str.is_empty(template) then
    return nil
  end
  return {
    label = label,
    href = context.base_url .. resolve_template(template, context),
    icon = icon,
  }
end

--- Resolve the `extra-links` metadata list into link entries.
--- Relative hrefs (starting with '/') are resolved against the repository URL
--- so site configuration stays portable across forks.
--- @param extra_meta table|nil The `widget.extra-links` metadata list
--- @param repo_url string The repository URL
--- @param extension_name string The extension name (for warnings)
--- @return table<integer, table> The resolved link entries
local function resolve_extra_links(extra_meta, repo_url, extension_name)
  local links = {}
  if type(extra_meta) ~= 'table' then
    return links
  end
  for _, item in ipairs(extra_meta) do
    local label = item['text'] and meta_to_label(item['text'])
    local href = item['href'] and str.stringify(item['href'])
    if str.is_empty(item['text'] and str.stringify(item['text'])) or str.is_empty(href) then
      log.log_warning(
        extension_name,
        "Ignoring 'widget.extra-links' entry without both 'text' and 'href'."
      )
    elseif not (href:sub(1, 1) == '/' or href:match('^https?://')) then
      log.log_warning(
        extension_name,
        "Ignoring 'widget.extra-links' entry '" .. str.stringify(item['text']) ..
        "': 'href' must start with '/' or 'http(s)://'."
      )
    else
      if href:sub(1, 1) == '/' then
        href = repo_url .. href
      end
      local entry = { label = label, href = href }
      local icon = item['icon'] and str.stringify(item['icon'])
      if not str.is_empty(icon) then
        entry.icon = icon
      end
      table.insert(links, entry)
    end
  end
  return links
end

--- Concatenate link groups with dividers between non-empty groups.
--- @param groups table<integer, table> List of link-entry lists
--- @return table<integer, table> The flat link list with divider entries
local function join_link_groups(groups)
  local links = {}
  for _, group in ipairs(groups) do
    if #group > 0 then
      if #links > 0 then
        table.insert(links, { divider = true })
      end
      for _, entry in ipairs(group) do
        table.insert(links, entry)
      end
    end
  end
  return links
end

--- Build the widget configuration table serialised for widget.js.
--- @param spec table See `widget_module.setup`
--- @return table The JSON-ready configuration
local function build_config(spec)
  local widget_meta = spec.widget_meta
  local platform_widget = spec.platform_config.widget or {}
  local paths = platform_widget.paths
  local labels = platform_widget.labels or {}
  local context = { repo = spec.repository_name, base_url = spec.base_url }
  local repo_url = spec.base_url .. '/' .. spec.repository_name
  local toggles = widget_meta['links']

  local main_group = {
    { label = 'Repository', href = repo_url, icon = 'repo' },
  }
  append_default_link(main_group, toggles, 'issues', true,
    platform_link(paths, 'issues', 'Issues', 'issue', context))
  append_default_link(main_group, toggles, 'pull-requests', true,
    platform_link(paths, 'pull_requests', labels.pull_requests or 'Pull Requests', 'pull-request', context))
  append_default_link(main_group, toggles, 'releases', true,
    platform_link(paths, 'releases', 'Releases', 'release', context))
  -- Discussions are off by default: not every repository has them enabled,
  -- so a default link would often be dead.
  append_default_link(main_group, toggles, 'discussions', false,
    platform_link(paths, 'discussions', 'Discussions', 'discussion', context))

  local action_group = {}
  append_default_link(action_group, toggles, 'star', true,
    platform_link(paths, 'star', 'Add a Star', 'star', context))
  append_default_link(action_group, toggles, 'fork', true,
    platform_link(paths, 'fork', 'Create a Fork', 'fork', context))

  local extra_group = resolve_extra_links(widget_meta['extra-links'], repo_url, spec.extension_name)

  local sponsor = widget_meta['sponsor'] and str.stringify(widget_meta['sponsor'])
  if not str.is_empty(sponsor) then
    local sponsor_template = platform_widget.sponsor_url
    if str.is_empty(sponsor_template) then
      log.log_warning(
        spec.extension_name,
        "Ignoring 'widget.sponsor': platform '" .. spec.platform .. "' defines no sponsor URL."
      )
    else
      context.username = sponsor
      table.insert(extra_group, {
        label = 'Sponsor',
        href = resolve_template(sponsor_template, context),
        icon = 'heart',
      })
    end
  end

  local icon = widget_meta['icon'] and str.stringify(widget_meta['icon'])
  if str.is_empty(icon) then
    icon = spec.platform == 'github' and 'mark-github' or 'git-branch'
  end

  local config = {
    cacheKey = 'gitlink-widget-' .. spec.platform .. '-' .. spec.repository_name,
    menuLabel = spec.display_name .. ' repository menu',
    icon = icon,
    links = join_link_groups({ main_group, action_group, extra_group }),
  }

  local api = platform_widget.api
  if api and not str.is_empty(api.endpoint) then
    -- Platform headers are "Name: value" strings in the YAML (map keys would
    -- be case-mangled); parse them here so widget.js gets a ready object.
    local headers = {}
    local has_headers = false
    for _, header in ipairs(api.headers or {}) do
      local name, value = str.stringify(header):match('^([^:]+):%s*(.+)$')
      if name then
        headers[name] = value
        has_headers = true
      end
    end
    config.api = {
      endpoint = resolve_template(api.endpoint, context),
      starsField = api.stars_field,
      forksField = api.forks_field,
      headers = has_headers and headers or nil,
    }
  end

  -- Embed only the octicon bodies this menu uses; names not in the set are
  -- left for widget.js to render as Bootstrap icons.
  local octicons = load_octicons(spec.extension_name)
  local used = {}
  local function add_icon(name)
    if name and octicons[name] then
      used[name] = octicons[name]
    end
  end
  add_icon(config.icon)
  if config.api then
    add_icon('star')
    add_icon('fork')
  end
  for _, link in ipairs(config.links) do
    add_icon(link.icon)
  end
  config.icons = used

  return config
end

--- Inject the widget dependency and configuration into the document.
--- No-op outside HTML output. Logs a warning and skips injection when the
--- repository name could not be resolved.
--- @param spec table Fields: extension_name (string), widget_meta (table),
--- platform (string), platform_config (table), base_url (string),
--- repository_name (string|nil), display_name (string)
--- @return nil
function widget_module.setup(spec)
  if not quarto.doc.is_format('html:js') then
    return
  end

  if str.is_empty(spec.repository_name) then
    log.log_warning(
      spec.extension_name,
      "Widget is enabled but no repository could be resolved. " ..
      "Set 'extensions.gitlink.repository-name' (owner/repo) or add a git remote."
    )
    return
  end

  local stylesheets = { quarto.utils.resolve_path('widget.css') }
  if to_boolean(spec.widget_meta['style-navbar-tools'], false) then
    table.insert(stylesheets, quarto.utils.resolve_path('widget-navbar-tools.css'))
  end

  html_mod.ensure_html_dependency({
    name = 'quarto-gitlink-widget',
    version = WIDGET_DEPENDENCY_VERSION,
    scripts = { quarto.utils.resolve_path('widget.js') },
    stylesheets = stylesheets,
  })

  local config = build_config(spec)
  -- `</` must not appear verbatim inside a script element, so escape it in
  -- the serialised JSON (JSON treats `\/` as `/`).
  local json = quarto.json.encode(config):gsub('</', '<\\/')
  quarto.doc.include_text(
    'in-header',
    '<script type="application/json" id="gitlink-widget-config">' .. json .. '</script>'
  )
end

return widget_module
