---
title: "Open Source License"
---

Quarto is open source software licensed under the [GNU GPL v2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html). We believe that it's better for everyone if the tools used for research and science are free and open. Reproducibility, widespread sharing of knowledge and techniques, and the leveling of the playing field by eliminating cost barriers are but a few of the shared benefits of free software in science.

The Quarto source code is available at <https://github.com/quarto-dev/>

Quarto is a registered trademark of RStudio. Please see our [trademark policy](http://localhost:5066/trademark.html) for guidelines on usage of the Quarto trademark.

Quarto also makes use of several other open-source projects, the distribution of which is subject to their respective licenses. Major components and their licenses include:

| Project                                                       | License                                                            |
|---------------------------------------------------------------|--------------------------------------------------------------------|
| [Pandoc](https://pandoc.org/)                                 | [GNU GPL v2](https://github.com/jgm/pandoc/blob/master/COPYING.md) |
| [Bootstrap 5.0](https://getbootstrap.com/docs/5.0/)           | [MIT](https://github.com/twbs/bootstrap/blob/v5.0.2/LICENSE)       |
| [Bootswatch 5.0](https://bootswatch.com/)                     | [MIT](https://github.com/thomaspark/bootswatch/blob/v5/LICENSE)    |
| [Deno](https://deno.land/)                                    | [MIT](https://github.com/denoland/deno/blob/main/LICENSE.md)       |
| [esbuild](https://esbuild.github.io/)                         | [MIT](https://github.com/evanw/esbuild/blob/master/LICENSE.md)     |
| [Dart Saas](https://sass-lang.com/dart-sass)                  | [MIT](https://github.com/sass/dart-sass/blob/main/LICENSE)         |
| [Observable Runtime](https://github.com/observablehq/runtime) | [ISC](https://github.com/observablehq/runtime/blob/main/LICENSE)   |
