---
title: "Trademark Policy"
---

::: {.callout-note appearance="simple"}
This policy is adapted directly from the WordPress Foundation's [trademark policy](https://wordpressfoundation.org/trademark-policy/) for the WordPress and WordCamp names and logos. We admire the job that WordPress has done building a thriving open source community while at the same time making possible a wide variety of WordPress related businesses. We hope that this policy will help us do the same for Quarto.
:::

## Goals

[RStudio, PBC](https://www.rstudio.com/about/) owns and oversees the trademark for the Quarto name and logo. We have developed this trademark usage policy with the following goals in mind:

1.  We'd like to make it easy for anyone to use the Quarto name or logo for community-oriented efforts that help spread and improve Quarto.

2.  We'd like to make it clear how Quarto-related businesses and projects can (and cannot) use the Quarto name and logo.

3.  We'd like to make it hard for anyone to use the Quarto name and logo to unfairly profit from, trick or confuse people who are looking for official Quarto resources.

Please note that it is not the goal of this policy to limit open source or commercial activity around Quarto. We actively encourage Quarto-based open source projects and businesses---our goal with this policy is to prevent confusion about the source of Quarto related software and services.

## Permission

Permission from RStudio is required to use the Quarto name or logo as part of any project, product, service, domain name, or company name.

We will grant permission to use the Quarto name and logo for projects that meet the following criteria:

-   The primary purpose of your project is to promote the spread and improvement of the Quarto software.

-   Your project is non-commercial in nature (it can make money to cover its costs or contribute to non-profit entities, but it cannot be run as a for-profit project or business).

-   Your project neither promotes nor is associated with entities that currently fail to comply with the GPL license under which Quarto is distributed.

If your project meets these criteria, you will be permitted to use the Quarto name and logo to promote your project in any way you see fit with these exceptions: (1) Please do not use Quarto as part of a domain name; and (2) We do not allow the use of the trademark in advertising, including AdSense/AdWords.

All other Quarto-related businesses or projects can use the Quarto name and logo to refer to and explain their services, but they cannot use them as part of a product, project, service, domain name, or company name and they cannot use them in any way that suggests an affiliation with or endorsement by the Quarto open source project.

The abbreviation "QMD" is not covered by the Quarto trademark and you are free to use it in any way you see fit.

## Examples

A consulting company can describe its business as "123 Publishing Services, offering Quarto consulting for publishers," but cannot call its business "The Quarto Consulting Company." Similarly, a business related to Quarto extensions can describe itself as "XYZ Extensions, the world's best Quarto extensions," but cannot call itself "The Quarto Extension Portal."

Similarly, it's OK to use the Quarto logo as part of a page that describes your products or services, but it is not OK to use it as part of your company or product logo or branding itself. Under no circumstances is it permitted to use Quarto as part of a domain name or top-level domain name.

When in doubt about your use of the Quarto name or logo, please contact RStudio at [permissions\@rstudio.com](mailto:permissions@rstudio.com) for clarification.
