
::: callout-note
## Quarto v1.2 Required

Support for {{< meta ssg-name >}} websites is a feature of Quarto v1.2. If you want to use this feature please download and install [Quarto v1.2](https://quarto.org/docs/download/) before proceeding.

If you are running the Quarto [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto) you should also be sure to have the latest version of that installed (v1.41.0 or greater).
:::

## Overview

{{< meta ssg-description >}}. Pages in {{< meta ssg-name >}} websites are typically written in plain markdown, so don't have a straightforward way to automatically and reproducibly incorporate computational output.

Using the Quarto `{{< meta format-name >}}-md` format, you can incorporate computational output (e.g. R or Python code that produces plots) into {{< meta ssg-name >}} websites. This article explains how.

It's important to note that many of the Quarto features related to theming, page layout, and navigation are not applicable when you are using Quarto with {{< meta ssg-name >}}. {{< meta ssg-name >}} has its own theming system, syntax highlighting, table of contents, page layout, navigational menus, and full text search. You'll use Quarto to execute code and generate markdown that is rendered within the {{< meta ssg-name >}} HTML publishing framework rather than Quarto's own.
