---
title: "HTML Customization Using Sass Variables"
---

In addition to some basic customization using `YAML` in the document front matter or Quarto project file, Quarto HTML output can be customized using Sass variables to control the generated CSS.

The following tables outline the most commonly used customizations. In addition to the below Sass variables, Bootstrap itself supports hundreds of additional variables. You can [learn more about Bootstrap's use of Sass variables](https://getbootstrap.com/docs/5.1/customize/sass/) or review the [raw variables and their default values](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss).

## Frequently Used Sass Variables

### Page Colors

+--------------------------+------------------------------------------------------------------------------------+
| Variable                 | Notes                                                                              |
+==========================+====================================================================================+
| `body-bg`                | The page background color.                                                         |
+--------------------------+------------------------------------------------------------------------------------+
| `body-color`             | The page text color.                                                               |
+--------------------------+------------------------------------------------------------------------------------+
| `link-color`             | The link color.                                                                    |
+--------------------------+------------------------------------------------------------------------------------+
| `input-bg`               | The background color for HTML inputs.                                              |
+--------------------------+------------------------------------------------------------------------------------+
| `popover-bg`             | The background color for popovers (for example, when a citation preview is shown). |
+--------------------------+------------------------------------------------------------------------------------+
| `font-family-sans-serif` | The sans-serif font family for the page.                                           |
+--------------------------+------------------------------------------------------------------------------------+
| `font-family-monospace`  | The monospace font family for the page.                                            |
+--------------------------+------------------------------------------------------------------------------------+

### Fonts

+--------------------------+------------------------------------------+
| Variable                 | Notes                                    |
+==========================+==========================================+
| `font-family-sans-serif` | The sans-serif font family for the page. |
+--------------------------+------------------------------------------+
| `font-family-monospace`  | The monospace font family for the page.  |
+--------------------------+------------------------------------------+
| `font-size-root`         | The base font size for the page.         |
+--------------------------+------------------------------------------+
| `toc-font-size`          | The font size for the page TOC.          |
+--------------------------+------------------------------------------+
| `h1-font-size`           | Font sizes for the specified headings.   |
|                          |                                          |
| `h2-font-size`           |                                          |
|                          |                                          |
| `h3-font-size`           |                                          |
|                          |                                          |
| `h4-font-size`           |                                          |
|                          |                                          |
| `h5-font-size`           |                                          |
+--------------------------+------------------------------------------+

## Quarto Specific Sass Variables

### Code Block Formatting

+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable                       | Notes                                                                                                                                                            |
+================================+==================================================================================================================================================================+
| `code-block-border-left`       | By default, Quarto does not display a left border on code blocks. Set this variable to a truthy value or a CSS color to enable the left border.                  |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-border-left-style` | The style of the left border displayed on code blocks. Defaults to `solid`.                                                                                      |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-border-left-size`  | The thickness of the left border displayed on code blocks. Defaults to `3px`;                                                                                    |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-padding-left`      | The amount of padding applied between the code and the border. Defaults to `0.6em`.                                                                              |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-bg`                | By default, Quarto sets a background on code blocks by adding transparency to the theme's `progress-bg` color. Set this variable to truthy value or a CSS color. |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-bg-padding`        | The padding applied to the code block. Defaults to `0.4em`.                                                                                                      |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `code-block-bg-alpha`          | The amount to alter the transparency fo the `progress-bg` color. This is not used if an explicit background color is set. Defaults to `-0.35`.                   |
+--------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Inline Code Formatting

+---------------+-------------------------------------------------------------------------------------------------+
| Variable      | Notes                                                                                           |
+===============+=================================================================================================+
| `code-bg`     | The background color of inline code. Defaults to a mix between the `body-bg` and `body-color`.  |
+---------------+-------------------------------------------------------------------------------------------------+
| `code-color`  | The text color of inline code. Defaults to a generated contrasting color against the `code-bg`. |
+---------------+-------------------------------------------------------------------------------------------------+

### Callout Appearance

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable                | Notes                                                                                                                                                              |
+=========================+====================================================================================================================================================================+
| `callout-border-width`  | By default, Quarto does not display a left border on code blocks. Set this variable to a truthy value or a CSS color to enable the left border. Defaults to `5px`. |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `callout-border-scale`  | The border color of callouts computed by shifting the callout color by this amount. Defaults to `0%`.                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `callout-icon-scale`    | The color of the callout icon computed by shifting the callout color by this amount. Defaults to `10%`.                                                            |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `callout-margin-top`    | The amount of top margin on the callout. Defaults to `1.25rem`.                                                                                                    |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `callout-margin-bottom` | The amount of bottom margin on the callout. Defaults to `1.25rem`.                                                                                                 |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `callout-color-<type>`  | The colors for the various types of callouts. Defaults:                                                                                                            |
|                         |                                                                                                                                                                    |
|                         | | type        | default   |                                                                                                                                        |
|                         | |-------------|-----------|                                                                                                                                        |
|                         | | `note`      | `$blue`   |                                                                                                                                        |
|                         | | `tip`       | `$green`  |                                                                                                                                        |
|                         | | `caution`   | `$orange` |                                                                                                                                        |
|                         | | `warning`   | `$yellow` |                                                                                                                                        |
|                         | | `important` | `$red`    |                                                                                                                                        |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Website Navigation Formatting

+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable     | Notes                                                                                                                                                                       |
+==============+=============================================================================================================================================================================+
| `navbar-bg`  | The background color of the navbar. Defaults to the theme's `$primary` color.                                                                                               |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `navbar-fg`  | The color of foreground elements (text and navigation) on the navbar. If not specified, a contrasting color is automatically computed.                                      |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `navbar-hl`  | The highlight color for links in the navbar. If not specified, the `$link-color` is used or a contrasting color is automatically computed.                                  |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sidebar-bg` | The background color for a sidebar. Defaults to `$light` except when a navbar is present or when the style is `floating`. In that case it defaults to the `$body-bg` color. |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sidebar-fg` | The color of foreground elements (text and navigation) on the sidebar. If not specified, a contrasting color is automatically computed.                                     |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sidebar-hl` | The highlight color for links in the sidebar. If not specified, the `$link-color` is used.                                                                                  |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `footer-bg`  | The background color for a sidebar. Defaults to the `$body-bg` color.                                                                                                       |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `footer-fg`  | The color of foreground elements (text and navigation) on the footer. If not specified, a contrasting color is automatically computed.                                      |
+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## 
