---
title: More Formats
description: "Pandoc support a huge array of output formats, all of which can be used with Quarto. To use any Pandoc format just use the `format` option or the `--to` command line option."
format: html
---

## Overview

Pandoc support a huge array of output formats, all of which can be used with Quarto. To use any Pandoc format just use the `format` option or the `--to` command line option.

For example, here's some YAML that specifies the use of the `odt` format as well as a couple of format options:

``` yaml
---
title: "My Document"
format: 
  odt:
    toc: true
    reference-doc: reference.odt
---
```

Alternatively you can specify the use of a format on the command line:

``` bash
quarto render document.qmd --to odt
```

## Formats

All Pandoc output formats currently available are listed below (the format "name" on the left is what you specify in the `format` YAML key).

To learn more about the specific options available for all of Pandoc's formats, see the [Pandoc User Guide](https://pandoc.org/MANUAL.html).

+------------------------+-------------------------------------------------------------------------------------------------------+
| Name                   | Details                                                                                               |
+========================+=======================================================================================================+
| asciidoc               | <https://asciidoc.org/>                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------+
| asciidoctor            | <https://asciidoctor.org/>                                                                            |
+------------------------+-------------------------------------------------------------------------------------------------------+
| beamer                 | <https://ctan.org/pkg/beamer>                                                                         |
+------------------------+-------------------------------------------------------------------------------------------------------+
| commonmark\            | <https://commonmark.org/>                                                                             |
| commonmark_x           |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| context                | <http://www.pragma-ade.nl/>                                                                           |
+------------------------+-------------------------------------------------------------------------------------------------------+
| csljson                | <https://citationstyles.org/>                                                                         |
+------------------------+-------------------------------------------------------------------------------------------------------+
| docbook\               | <https://www.docbook.org/>                                                                            |
| docbook4\              |                                                                                                       |
| docbook5               |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| docx                   | <https://en.wikipedia.org/wiki/Office_Open_XML>                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| dokuwiki               | <https://www.dokuwiki.org/wiki:syntax>                                                                |
+------------------------+-------------------------------------------------------------------------------------------------------+
| dzslides               | <http://paulrouget.com/dzslides/>                                                                     |
+------------------------+-------------------------------------------------------------------------------------------------------+
| epub\                  | <https://en.wikipedia.org/wiki/EPUB>                                                                  |
| epub2\                 |                                                                                                       |
| epub3                  |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| fb2                    | <https://en.wikipedia.org/wiki/FictionBook>                                                           |
+------------------------+-------------------------------------------------------------------------------------------------------+
| gfm                    | <https://github.github.com/gfm/>                                                                      |
+------------------------+-------------------------------------------------------------------------------------------------------+
| haddock                | <https://haskell-haddock.readthedocs.io/>                                                             |
+------------------------+-------------------------------------------------------------------------------------------------------+
| html\                  | <https://en.wikipedia.org/wiki/HTML5>                                                                 |
| html4\                 |                                                                                                       |
| html5                  |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| icml                   | <https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf> |
+------------------------+-------------------------------------------------------------------------------------------------------+
| ipynb                  | <https://nbformat.readthedocs.io/>                                                                    |
+------------------------+-------------------------------------------------------------------------------------------------------+
| jats\                  | <https://jats.nlm.nih.gov/publishing/>                                                                |
| jats_archiving\        |                                                                                                       |
| jats_articleauthoring\ |                                                                                                       |
| jats_publishing        |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| jira                   | <https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all>                           |
+------------------------+-------------------------------------------------------------------------------------------------------+
| json                   | <https://pandoc.org/filters.html>                                                                     |
+------------------------+-------------------------------------------------------------------------------------------------------+
| latex                  | <https://www.latex-project.org/>                                                                      |
+------------------------+-------------------------------------------------------------------------------------------------------+
| man                    | <https://www.gnu.org/software/groff/groff.html>                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| markdown\              | <https://pandoc.org/MANUAL.html#markdown-variants>                                                    |
| markdown_github\       |                                                                                                       |
| markdown_mmd\          |                                                                                                       |
| markdown_phpextra\     |                                                                                                       |
| markdown_strict        |                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| mediawiki              | <https://www.mediawiki.org/wiki/Help:Formatting>                                                      |
+------------------------+-------------------------------------------------------------------------------------------------------+
| ms                     | <https://www.gnu.org/software/groff/groff.html>                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------+
| muse                   | <https://www.gnu.org/software/emacs-muse/manual/>                                                     |
+------------------------+-------------------------------------------------------------------------------------------------------+
| native                 | <https://pandoc.org/using-the-pandoc-api.html>                                                        |
+------------------------+-------------------------------------------------------------------------------------------------------+
| odt                    | <https://en.wikipedia.org/wiki/OpenDocument>                                                          |
+------------------------+-------------------------------------------------------------------------------------------------------+
| opendocument           | <http://opendocument.xml.org/>                                                                        |
+------------------------+-------------------------------------------------------------------------------------------------------+
| opml                   | <https://en.wikipedia.org/wiki/OPML>                                                                  |
+------------------------+-------------------------------------------------------------------------------------------------------+
| org                    | <https://orgmode.org/>                                                                                |
+------------------------+-------------------------------------------------------------------------------------------------------+
| pdf                    | <https://en.wikipedia.org/wiki/PDF>                                                                   |
+------------------------+-------------------------------------------------------------------------------------------------------+
| plain                  | Plain text                                                                                            |
+------------------------+-------------------------------------------------------------------------------------------------------+
| pptx                   | <https://en.wikipedia.org/wiki/Microsoft_PowerPoint>                                                  |
+------------------------+-------------------------------------------------------------------------------------------------------+
| revealjs               | <https://revealjs.com/>                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------+
| rst                    | <https://docutils.sourceforge.io/rst.html>                                                            |
+------------------------+-------------------------------------------------------------------------------------------------------+
| rtf                    | <https://en.wikipedia.org/wiki/Rich_Text_Format>                                                      |
+------------------------+-------------------------------------------------------------------------------------------------------+
| s5                     | <http://meyerweb.com/eric/tools/s5/>                                                                  |
+------------------------+-------------------------------------------------------------------------------------------------------+
| slideous               | <http://goessner.net/articles/slideous/>                                                              |
+------------------------+-------------------------------------------------------------------------------------------------------+
| slidy                  | <http://www.w3.org/Talks/Tools/Slidy>                                                                 |
+------------------------+-------------------------------------------------------------------------------------------------------+
| tei                    | <https://github.com/TEIC/TEI-Simple>                                                                  |
+------------------------+-------------------------------------------------------------------------------------------------------+
| texinfo                | <https://www.gnu.org/software/texinfo/>                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------+
| textile                | <https://www.promptworks.com/textile>                                                                 |
+------------------------+-------------------------------------------------------------------------------------------------------+
| xwiki                  | <https://www.xwiki.org/>                                                                              |
+------------------------+-------------------------------------------------------------------------------------------------------+
| zimwik                 | <https://zim-wiki.org/>                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------+
