---
title: "Quarto Dashboards"
---

{{< include ../_pre-release-feature.qmd >}}

## Overview

Quarto Dashboards make it easy to create interactive dashboards using Python, R, Julia, and Observable JS:

-   Publish a group of related data visualizations as a dashboard.

-   Support for a wide variety of components including [Plotly](https://plotly.com/python/), [Leaflet](https://ipyleaflet.readthedocs.io/en/latest/), [Jupyter Widgets](/docs/interactive/widgets/jupyter.qmd), [htmlwidgets](https://www.htmlwidgets.org/); static graphics (Matplotlib, Seaborn, ggplot2, etc.); tabular data; value boxes; and text annotations.

-   Flexible and easy to specify row and column-based [Layouts](layouts.qmd). Components are intelligently re-sized to fill the browser and adapted for display on mobile devices.

-   Add interactive inputs using [Py Shiny](/docs/prerelease/1.4/shiny/index.qmd), [R Shiny](/docs/interactive/shiny/), and [Observable JS](/docs/interactive/ojs/) to drive visualizations dynamically.

-   Author using any notebook editor ([JupyterLab](/docs/tools/jupyter-lab.qmd), etc.) or in plain text markdown with any text editor ([VS Code](/docs/tools/vscode.qmd), [RStudio](/docs/tools/rstudio.qmd), [Neovim](/docs/tools/neovim.qmd), etc.)

## Examples

