## Overview

Shortcodes are special markdown directives that generate various types of content. Quarto shortcodes are similar in form and function to [Hugo shortcodes](https://gohugo.io/content-management/shortcodes/) and [WordPress shortcodes](https://codex.wordpress.org/Shortcode).

For example, the following shortcode prints the `title` from document metadata:

``` {.markdown shortcodes="false"}
{{< meta title >}}
```

## Built-in Shortcodes

Quarto supports several shortcodes natively:

| Shortcode                                                     | Description                              |
|---------------------------------------------------------------|------------------------------------------|
| [version](/docs/authoring/version.qmd)                        | Print Quarto CLI version                 |
| [var](/docs/authoring/variables.qmd#var)                      | Print value from `_variables.yml` file   |
| [meta](/docs/authoring/variables.qmd#meta)                    | Print value from document metadata       |
| [env](/docs/authoring/variables.qmd#url)                      | Print system environment variable        |
| [pagebreak](/docs/authoring/markdown-basics.qmd#page-breaks)  | Insert a native page-break               |
| [kbd](/docs/authoring/markdown-basics.qmd#keyboard-shortcuts) | Describe keyboard shortcuts              |
| [video](/docs/authoring/videos.qmd)                           | Embed a video in a document              |
| [include](/docs/authoring/includes.qmd)                       | Include contents of another qmd          |
| [embed](/docs/authoring/notebook-embed.qmd)                   | Embed cells from a Jupyter Notebook      |
| [placeholder](/docs/authoring/placeholder.qmd)                | Add placeholder images to your document  |
| [lipsum](/docs/authoring/lipsum.qmd)                          | Add placeholder text to your document    |
| [contents](/docs/authoring/contents.qmd)                      | Rearrange content in your document       |
