---
title: Multiformat branding with `_brand.yml`
draft: true
---

## Introduction

Quarto supports a wide variety of formats, and allows powerful customization of your document's appearance
in each of those formats. 
`_brand.yml` enables a different form of appearance customization.
This feature is particularly well-suited for organizations that need a unified look across multiple formats with little per-format work.

## Hello, `_brand.yml`

Consider the following `hello-brand.qmd` document in a folder that contains the following `_brand.yml` file:

::: {.panel-tabset}

## `hello-brand.qmd`

```qmd
---
format:
  html: default
  revealjs: default
  dashboard: default
  typst: default
  pdf: default
---

## Hello, `_brand.yml`

Find out more in the [documentation](https://prerelease.quarto.org/docs/authoring/brand.html)

```

## `_brand.yml`

```yml
color:
  with:
    orange: '#a55930'
  primary: orange
```

:::

These are the resulting documents:

::: {.panel-tabset}

## `html`

TBF.

## `dashboard`

TBF.

## `revealjs`

TBF.

## `typst`

TBF.

## `pdf`

TBF.

:::

## Using `_brand.yml` values

### Shortcode - `{{{< brand >}}}`

Values from the `_brand.yml` configuration file can be accessed via the `brand` shortcode.

- `{{{< brand color COLOR_NAME >}}}` resolves `COLOR_NAME` to the appropriate color value
- `{{{< brand logo LOGO_NAME >}}}
- TBD: what should `{{{< brand typography ... >}}}` resolve to?

### Lua API

```lua
local brand = require('modules/brand/brand')
local primary = brand.get_color('primary')
```

## Spec

TBF. Link to posit-wide documentation?

### `color`

### `typography`

### `logo`

### `defaults`
