---
title: Adding Placeholder Text to Your Documents
aliases:
  - /docs/prerelease/1.5/lipsum.html
---

## Overview

When you need to visualize how text will look in your document or your website, the `{{{< lipsum >}}}` shortcode comes in handy.
It inserts "Lorem Ipsum" dummy text, which is standard placeholder text used in the publishing and design industries.

## Example

Here's an example of `lipsum` generating two paragraphs of text, by adding `{{{< lipsum 2 >}}}` in a paragraph by itself.

{{< lipsum 2 >}}

## Usage

::: {layout-ncol=1}
```markdown
{{{< lipsum 1 >}}}
```
:::: {.border}
{{< lipsum 1 >}}
::::
:::

`lipsum` takes an optional parameter, in two possible formats:

- `{{{< lipsum nparas >}}}`: `nparas` describes the number of paragraphs of placeholder text to include in the document. 
- `{{{< lipsum start-end >}}}`: `start` and `end` are two numbers that describe the range of lorem ipsum paragraphs to include in the document.

`lipsum` produces placeholder text in a predictable manner[^1]. This means that the same parameters will always yield identical text.
However, you can choose to set `random=true` to generate a paragraph or a random collection of paragraphs.


- `{{{< lipsum 1 random=true >}}}`: This will generate a single paragraph of random lorem ipsum text.

[^1]: Since 1.7.14. Earlier versions of Quarto generates random text.
