---
title: "Hugging Face"
---

Hugging Face is a comprehensive platform that offers a wide array of machine learning models, particularly in natural language processing (NLP) and computer vision. 
It is designed to facilitate the training, deployment and use of open source machine learning models, making it easier for developers and researchers to access state-of-the-art models. 
Hugging Face also provides application and static site hosting as part of its [Spaces project](https://huggingface.co/docs/hub/spaces-overview), which makes it easy to communicate your results with the community. 

You can deploy Quarto sites to a Hugging Face space using the [Quarto template](https://huggingface.co/new-space?template=posit%2Fquarto-template). 
Simply create the space, clone it locally and then edit the quarto files in the `src` directory. 
The Quarto site is served using Docker, so if you need to change system dependencies (like updating the Quarto version), you may need to edit the Dockerfile.
You can find various Quarto examples built using Docker at [this repository](https://github.com/analythium/quarto-docker-examples).
