---
title: "RStudio Connect"
editor: visual
---

## Overview

-   asdf
-   asdfasdf
-   adsfasdf

Don't worry, Airflow is supported!

<https://docs.rstudio.com/connect/user/quarto/>

## Publishing Content

Easiest, simplest, probably fine if you don't know any better.

quarto publish

## Publishing with Code

why: reproducibility, reports, updating w/ new data automatically

https://docs.rstudio.com/resources/install-quarto/

We'll cover command line publishing, IDE integration (RStudio) as well.

-   quarto r package

-   rsconnect-python package

-   IDE publishing

    -   RStudio: <https://docs.rstudio.com/connect/user/publishing/>

    -   Jupyter: <https://docs.rstudio.com/connect/user/publishing-cli-quarto/>

    -   

## Publishing from Git

https://docs.rstudio.com/resources/install-quarto/

<https://github.com/rstudio/connect/tree/main/docs>

https://github.com/rstudio/connect/tree/main/docs/user/docs

### Manifest

<https://docs.rstudio.com/connect/user/git-backed/>

### GitHub Action

During development you might want to setup a GitHub Action to push to a staging server.

Manifest already exists.

Sample GH Action code for Python and R

## Continuous Integration

How to use use `quarto publish connect` in a headless environment (use for airflow, jenkins, etc.)

Just pushing output to connect.
