# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import seaborn as sns
penguins = sns.load_dataset("penguins")
species = list(penguins["species"].value_counts().index)
islands = list(penguins["island"].value_counts().index)

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny import render, reactive, ui
    ui.input_checkbox_group(
        "species", "Species:", 
        species, selected = species
    )

    # ========================================================================

    ui.input_checkbox_group(
        "islands", "Islands:", 
        islands, selected = islands
    )

    # ========================================================================

    ui.input_select("dist", "Distribution:", choices=["kde", "hist"])
    ui.input_checkbox("rug", "Show rug marks", value = False)

    # ========================================================================

    @reactive.Calc
    def filtered_penguins():
        data = penguins[penguins["species"].isin(input.species())]
        data = data[data["island"].isin(input.islands())]
        return data

    # ========================================================================

    @render.plot
    def depth():
        return sns.displot(
            filtered_penguins(), x = "bill_depth_mm", 
            hue = "species", kind = input.dist(), 
            fill = True, rug=input.rug()
        )

    # ========================================================================




_static_assets = ["column-layout_files"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "column-layout.html",
    server,
    static_assets=_static_assets,
)
