---
title: "Creating Formats"
---

### Format Extensions

Formats provided by extensions can be used as a format key in document or project metadata or as a target of the `--to` argument when rendering (or both). Since format extensions *extend* the existing formats provided by Quarto, they are targeted using both the extension name and the output format name (separated by a '-'):

`quarto render mydocument.qmd —to <extension-name>-pdf`

or

``` yaml
---
title: My Document
format: 
  <extension-name>-pdf:
    cite-method: natbib
---
```

To use a filter extension, first install the extension using `quarto install extension`. Once installed, use the format as a render target. For example, to use the format for rendering the `Journal of Statistical Software`, install the extension using:

`quarto install extension quarto-journals/jss`

then render a document such as:

``` markdown
---
title: My JSS Document
format:
  pdf: default
  jss-pdf:
    keep-tex: true  
  # also valid
  # quarto-ext/jss-pdf
author:
  - Norah Jones
---

## Welcome to My Document!
```

Format extensions can target multiple output formats, which can be targeted independently. For example:

``` markdown
---
title: My JSS Document
format:
  pdf: default
  jss-pdf:
    keep-tex: true  
  jss-html:
    highlight-style: solarized
author:
  - Norah Jones
---

## Welcome to My Document!
```
