---
title: "Knitr Layout"
author: "Jane Doe"
date: "March 22nd, 2021"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

::: {.callout-tip}
## Learn more
See the full guide on [Figures](https://quarto.org/docs/authoring/figures.html) and [Article Layout](https://quarto.org/docs/authoring/article-layout.html).
:::

## Use knitr `fig-ncol`

```` {.markdown}
```{r}
#| label: fig-panel
#| fig-cap: "Panel"
#| fig-subcap: ["cars", "mtcars", "pressure"]
#| fig-ncol: 3
```
````

```{r}
#| label: fig-panel
#| fig-cap: "Panel"
#| fig-subcap: ["cars", "mtcars", "pressure"]
#| fig-ncol: 3
plot(cars)
plot(pressure)
plot(mtcars)
```

## Use `layout` 

```` ```{r, layout=list(c(45,-10, 45), c(100))} ````

```{r, layout=list(c(45,-10, 45), c(100))}
plot(cars)
plot(pressure)
plot(mtcars)
```


## Layout tables

```` ```{r, layout-ncol=2} ````

```{r}
#| layout-ncol: 2

library(knitr)
kable(head(cars), caption = "Cars")
kable(head(pressure), caption = "Pressure")
```


