#### Website Draft Mode

Quarto websites now have improved support for workflows involving draft posts and pages. Learn more about our [new draft support](/docs/prerelease/1.5/website-drafts.qmd).

#### Project Pre Render Scripts

Previously, project metadata and the project render list were loaded prior to executing any pre-render scripts for a project. This prevented these pre-render scripts from modifying any project metadata or adding to the render list (for example by generating `qmd` files or `ipynb` files that should be rendered).

Starting in Quarto 1.5, the project metadata and render list will be re-computed after any pre-render scripts have executed, allowing them to modify this project data.

Note that pre-render scripts cannot modify the project directory, the output directory, or the project type. If a pre-render script modifies any of these values, an error will be returned and the render will fail.

#### Element-wide disabling of HTML processing

Quarto 1.5 provides [additional control](/docs/prerelease/1.5/lua-table-processing.qmd) for its table processing.