---
title: Website Draft Support
---

{{< include _pre-release-feature.qmd >}}

## New in Quarto 1.5

This feature improves Quarto's support for draft documents in websites. It does this a few ways:

-   Adds the `drafts` option to the `website` key offering new ways to specify drafts: directly in `_quarto.yml`, and via metadata includes and profiles.

-   Introduces the `draft-mode` option to the `website` key to control how drafts are rendered. Drafts can be `gone`, `unlinked` or `visible`.

-   Adds a draft banner to draft pages that are rendered.

-   Improves the linking behaviour of draft documents. Now, in addition to being excluded from search results, listings, and the sitemap, drafts will not appear in navigation, or be linked from in-text hyperlinks when `draft-mode` is `gone` or `unlinked`. 

-   Changes the behavior of `quarto preview` for drafts. Drafts will be `visible` in previews regardless of the `draft-mode` setting. In particular, this allows an easier way to preview the appearance of draft content in navigation and listings. 

Read more about these changes at [Website Drafts](/docs/websites/website-drafts.qmd).

