---
title: AsciiDoc Books
---

{{< include _pre-release-feature.qmd >}}

## Overview

[AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) is a text-based format that is often used to submit manuscripts to technical book publishers, including [O'Reilly](https://www.oreilly.com) and [Manning](https://www.manning.com).

Using the Quarto `asciidoc` format, you can incorporate computational output and other features of Quarto (such as callouts, code annotations, and more) into AsciiDoc books. This article explains how.

## Setup

Adding AsciiDoc output to a Quarto book project is straightforward. You can simply add the `asciidoc` format to the list of the output formats, like so:

``` yaml
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  asciidoc: default
```

When your book project is rendered, the AsciiDoc output will be placed in a sub-directory of the output folder, by default in `_book/book-asciidoc`.

## Workflow

While you are working on your book, we recommend that you preview your content using Quarto's built in HTML format, which allows a iterative workflow using the preview capabilities of Quarto:

``` bash
quarto preview mybook
```

If you have included the `asciidoc` format as described above it will be automatically rendered into theh `_book` directory when the book is rendered:

``` bash
quarto render mybook
```

If you want to render *only* the `asciidoc` format you can do this:

``` bash
quarto render mybook --to asciidox
```

When you are close to submitting your book for publication you will likely also want to preview the book's AsciiDoc output as described in [Previewing AsciiDoc Content].

## Structure

Asciidoc books support the full structure of Quarto books, including parts, chapters, and appendices. Chapters and appendices of AsciiDoc books are rendered as individual files, with an `adoc` file being produced for each chapter and appendix in your book. Each of the files will be named based upon the input, with the exception of the root page of the book, which is handled specially and named based upon the title of your book.

### Root Book File

A root book file will be generated for the book. This page will provide the 'front matter' for the book (title, author, and so on) and be based upon any content that appears in your `index.qmd` file. It will use AsciiDoc `include` directives to reference the various chapters, parts, and appendices of your book (as well as the bibliography, if present). A simple root book file looks like:

``` markdown
= Sample Book
Norah Jones
2/1/23
:toc:
:doctype: book

== 1. Preface

This is a Quarto book.

To learn more about Quarto books visit https://quarto.org/docs/books.

:leveloffset: +1

include::intro.adoc[]

include::summary.adoc[]

include::references.adoc[]

:leveloffset: -1
```

## Previewing AsciiDoc Content

While you are working on your book, we recommend that you preview your content using Quarto's built in HTML format, which allows a iterative workflow using the preview capabilities of Quarto. Once you're ready to produce AsciiDoc, you can use the AsciiDoctor tools to compile your book to PDF or HTML output to preview the content in its final rendered form.

### Previewing PDF with Asciidoctor-pdf

Creating a PDF preview with the AsciiDoc toolchain is a useful way to verify that the AsciiDoc output of your book can be rendered properly. To do this, follow these instructions:

1.  First, install Asciidoctor PDF by following the instructions here: <https://docs.asciidoctor.org/pdf-converter/latest/install/>

2.  From the terminal in the root of your project, use the following command to compile your AsciiDoc book to a PDF:

``` bash
$  asciidoctor-pdf _book/book-asciidoc/<title>.adoc
```

3.  The PDF will be placed at `_book/book-asciidoc/<title>.pdf`.

### Previewing HTML with Asciidoctor

Creating an HTML preview the AsciiDoc toolchain is a useful way to verify that the AsciiDoc output of your book can be rendered properly. To do this, follow these instructions:

1.  First, install Asciidoctor by following the instructions here: <https://docs.asciidoctor.org/asciidoctor/latest/install/>

2.  From the terminal in the root of your project, use the following command to compile your AsciiDoc book to a PDF:

``` bash
$  asciidoctor _book/book-asciidoc/<title>.adoc
```

3.  A single HTML file (with the entire contents of the book) will be placed at `_book/book-asciidoc/<title>.html`. Note that the HTML file will contain references to files and images in the `_book/book-asciidoc/` folder, so the HTML will not display these properly if moved without also moving those folders.

::: callout-note
## Asciidoc vs Asciidoctor Format

Pandoc includes support for both the `asciidoc` and `asciidoctor` formats. The `asciidoc` format produces older style syntax that is no longer typically used, while the `asciidoctor` format produces the more current markdown syntax that is part of the formal AsciiDoc specification.

In Quarto, both `asciidoc` and `asciidoctor` are aliases for the `asciidoctor` format.
:::