---
title: "Pandoc 3.1"
---

{{< include _pre-release-feature.qmd >}}

## Overview

Quarto 1.3 ships with Pandoc 3.1. For most users, the change from Pandoc 2.19 should be invisible. For users who routinely use Lua filters, though, there are some changes worth noting.

### Lua filters: `Figure` AST node

Pandoc ships with support for a new [`Figure` AST node](https://pandoc.org/lua-filters.html#type-figure) in its readers and writers.
This means that user filters in quarto will now have to process `Figure` nodes directly, instead of the "implicit figure" setup that previously consisted of a `Para` node containing a single `Image`.

## Limitations

- no support for `chunkedhtml`. Pandoc 3.1 adds a new output format `chunkedhtml`, which causes Pandoc to split a single document into multiple output html files. Quarto does not support `chunkedhtml`, and will produce unpredictable results when this output format is requested.

## Additional Reading

For full details on Pandoc's changes, consult their changelog file, specifically the sections from [3.0](https://github.com/jgm/pandoc/blob/main/changelog.md#pandoc-30-2023-01-18) through [3.1](https://github.com/jgm/pandoc/blob/main/changelog.md#pandoc-31-2023-02-09).
