Quarto can generate cross references that keep track of numbering and linking for you. The general syntax for a cross reference is an `@` followed by a label. For example, to reference the timeline figure, you could write:

``` markdown
@fig-timeline
```

When rendered, cross references include a word to indicate the type of object being referenced, like "Figure" or "Table". So for instance, this line in `{{< meta tool.article-file >}}`:

``` markdown
Eight eruptions have been recorded since the late 1400s (@fig-timeline).
```

Results in the text:

> Eight eruptions have been recorded since the late 1400s (Figure 1).

Where "Figure 1" is also a link to the appropriate figure.

The labels you add to elements must have the appropriate prefix to allow cross referencing:

| Element  | Label Prefix | Rendered Cross Reference |
|----------|--------------|--------------------------|
| Figure   | `fig-`       | Figure 1                 |
| Table    | `tbl-`       | Table 1                  |
| Equation | `eq-`        | Equation 1               |
| Section  | `sec-`       | Section 1                |

You've already seen you can add a label to output generated by code using the `label` code chunk option. You'll see how to add labels to non-code generated elements, like [equations](#equations), [tables](#tables), and [static figures](#static-figures), as you learn about them below.

To cross reference sections your document YAML header must also include:

```yaml
number-sections: true
```

You can add a label to a section heading in curly braces after the heading, e.g:

```markdown
## Data & Methods {#sec-data-methods}
```

You can then reference this section in the text, like:

```markdown
Data and methods are discussed in @sec-data-methods.
```

Which will be rendered as:

> Data and methods are discussed in Section 2.

You can read more about the types of objects that can be referenced, including code listings, and mathematical theorems, as well as some of the options to control how references appear in the Quarto [Cross References](/docs/authoring/cross-references.html) documentation.


::: {.content-visible unless-meta="tool.is_jupyterlab"}

In the Visual Editor, you can use **Insert -> Cross Reference** to get a dialog box with the available labels in your document and quickly generate the syntax needed for a cross reference.
:::
