The YAML header consists of key-value pairs set using the syntax `key: value`. The header is often extensive for articles because it is used to specify much of the scholarly front matter, like the authors and their affiliations, and the abstract.

::: {.callout-tip appearance="simple" collapse="true"}
## Expand to see full YAML header for `{{< meta tool.article-file >}}`

``` yaml
title: La Palma Earthquakes
author:
  - name: Steve Purves
    orcid: 0000-0002-0760-5497
    corresponding: true
    email: steve@curvenote.com
    roles:
      - Investigation
      - Project administration
      - Software
      - Visualization
    affiliations:
      - Curvenote
  - name: Rowan Cockett
    orcid: 0000-0002-7859-8394
    corresponding: false
    roles: []
    affiliations:
      - Curvenote
keywords:
  - La Palma
  - Earthquakes
abstract: |
  In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). ...
plain-language-summary: |
  Earthquake data for the island of La Palma from the September 2021 eruption is found ...
key-points:
  - A web scraping script was developed to pull data from the Instituto Geogràphico Nacional into a machine-readable form for analysis
  - Earthquake events on La Palma are consistent with the presence of both mantle and crustal reservoirs.
date: last-modified
bibliography: references.bib
citation:
  container-title: Earth and Space Science
number-sections: true
```
:::

For example, at the top level the header in `{{< meta tool.article-file >}}` sets the following keys: `title`, `author`, `keywords`, `abstract`, `plain-language-summary`, `key-points`, `date`, `bibliography`, `citation`, and `number-sections`.

You've seen how editing the `title` key updated the title of the article on the manuscript webpage. The `title` key is also used by the PDF and Word formats, but not all of the keys are used in all formats. For instance, `keywords` is not used in the HTML, PDF or Word formats, but it is used inside the MECA archive.

You can read more about setting the front matter for your article in [Scholarly Front Matter](/docs/authoring/front-matter.qmd).
