::: {.content-visible when-meta="tool.is_jupyterlab"}
Markdown cells in the document will be processed by Quarto's specific markdown syntax. Quarto's markdown syntax is based on [Pandoc Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown), which in turn is based on John Gruber's [Markdown](https://daringfireball.net/projects/markdown/), the same markdown Jupyter Notebooks use. You'll find much of the syntax, for example, text formatting like bold, italics, and verbatim code, as well as headings, links and lists familiar:
:::

::: {.content-visible unless-meta="tool.is_jupyterlab"}
Markdown cells in the document will be processed by Quarto's specific markdown syntax. Quarto's markdown syntax is based on [Pandoc Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown), which in turn is based on John Gruber's [Markdown](https://daringfireball.net/projects/markdown/). Some examples of basic syntax are shown below:
:::

{{< include _markdown-table.qmd >}}

If you want to see more syntax, this table is a subset of the features described in the Quarto documentation of [Markdown Basics](/docs/authoring/markdown-basics.html). 

As an example, the markdown to create the heading for the article's introduction is:

```markdown
## Introduction
```

First level headings are reserved for the article title, so you'll use second level and higher headings to structure the sections in your article.

::: {.content-visible when-meta="tool.is_jupyterlab"}
::: callout-tip
## Raw and Rendered Markdown

The Quarto extension for Jupyter Lab will attempt to display markdown cells as they will appear in rendered form. To see the raw markdown, enter "Edit mode" for the cell. To return to viewing the rendered markdown, "Run" the cell.
:::
:::

