On this page, we'll show you how to author an academic manuscript with Quarto in {{< meta tool.name >}}. You'll learn how to:

-   Preview your manuscript using {{< meta tool.name >}}.

-   Add scholarly front matter to describe your article.

-   Add figures, tables, cross references, and citations with Quarto-specific markdown.

-   Include output from computations using inline code or embedded from external notebooks.

::: {.content-visible when-meta="tool.is_jupyterlab"}
The commands and syntax you'll learn will apply to any tool you might use to edit notebooks, not just Jupyter Lab. And, although we'll use Python code examples, Quarto works with any kernel, so you could use R or Julia instead. 
:::

::: {.content-visible when-meta="tool.is_rstudio"}
The syntax you'll learn will apply regardless of the tool you are using to edit notebooks. And although we'll use R code examples, you could use Python or Julia instead. 
:::

::: {.content-visible when-meta="tool.is_vscode"}
The syntax you'll learn will apply regardless of the tool you are using to edit notebooks. And although we'll use Python code examples, you could use R or Julia instead. 

::: callout-tip

## Do you mostly use `.ipynb`?

As a VS Code user, we recommend writing your article in a `.qmd` file. However, if you currently use VS Code primarily to work with `.ipynb` files, you may find the Jupyter Lab tutorial more applicable. Install the [Quarto extension for Jupyter Lab](#install-the-quarto-vs-code-extension), then pick up the Jupyter Lab tutorial at [Clone the Template Repository](jupyterlab.qmd#clone-repo). You might also like read about using [Quarto with VS Code's Notebook Editor](/docs/tools/vscode-notebook.html).
:::

:::

::: {.content-visible when-meta="tool.is_rstudio"}

::: callout-caution

## What's a notebook?

You'll see us refer to Quarto documents (`.qmd`) as notebooks throughout this tutorial. In fact, we'll use the term "notebook"  interchangeably to refer to a Quarto document (`.qmd`) or a Jupyter Notebook (`.ipynb`). Although there are implementation differences these formats are both designed to combine code and narrative - a feature that is central to being a computational notebook.

When Quarto prepares your manuscript for publication, both as website and a submission archive, your Quarto `.qmd` documents and their outputs will be made available as Jupyter notebooks. Jupyter Notebooks have the advantage that computational outputs are included in the notebook file - allowing a record of both your code and its results to travel through the publication process and become part of your manuscript's document of record.

:::

:::

### Is this tutorial for me?

We will assume you:

-   are comfortable using {{< meta tool.name >}} to open and edit files,
-   have a GitHub account, and are comfortable cloning a repo to your computer,
-   are comfortable navigating your file system, and executing commands in a Terminal.
