project:
  type: website
  render:
    - index.qmd
    - talks.qmd
    - about.qmd

format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly

website:
  title: "My Site"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - about.qmd
