project:
  type: website

website:
  title: "My Site"
  sidebar:
    style: floating
    contents:
      - section: "Tutorials"
        contents:
          - text: "Tutorial Landing"
            href: tutorials.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [darkly, theme-dark.scss]
