project:
  type: website
  render:
    - about-jolla.qmd
    - about-trestles.qmd
    - about-solana.qmd
    - about-marquee.qmd
    - about-broadside.qmd

website:
  title: "About Pages"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
