---
title: External servers used by Quarto documents
---

The HTML files produced by Quarto (`html` documents, `dashboard`s, and `revealjs` presentations) are designed to minimize external dependencies.

However, on occasion, these documents might access resources hosted in external servers.
The following is a list of such situations:

- For jupyter widgets support:
  - `cdn.jsdelivr.net`
- If Google analytics support is enabled in websites:
  - `www.googletagmanager.com`
  - `www.google-analytics.com`
- If `webtex` is chosen to be the default math rendering method:
  - `latex.codecogs.com`
- If multiplex mode in `revealjs` is enabled:
  - `reveal-multiplex.glitch.me`
- For a number of revealjs and bootswatch themes:
  - `fonts.googleapis.com`
- For Quarto's internal debugging tools:
  - `esm.sh`
  - `cdn.skypack.dev`
- For giscus support:
  - `giscus.app`
- For the `placeholder` shortcode:
  - `svg2png.deno.dev`
- For the `video` shortcode:
  - `www.youtube-nocookie.com`
  - `players.brightcove.net`
  - `www.youtube.com`
  - `vimeo.com`
  - `youtu.be`
- For documents with OJS content:
  - `static.observableusercontent.com`
  - `cdn.observableusercontent.com`
  - `cdn.jsdelivr.net`
  - `unpkg.com`
