project:
  type: website
  render:
    - index.qmd
    - tutorials.qmd
    - tutorial-1.qmd
    - tutorial-2.qmd
    - howto.qmd
    - fundamentals.qmd
    - reference.qmd

format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly

website:
  title: "ProjectX"
  navbar:
    background: primary
    search: true
