project:
  output-dir: docs-dropdown

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:tutorials
      - sidebar:howto
      - sidebar:fundamentals
      - sidebar:reference

  sidebar:
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - tutorials.qmd
        - tutorial-1.qmd
        - tutorial-2.qmd

    - id: howto
      title: "How-To"
      contents:
        - howto.qmd

    - id: fundamentals
      title: "Fundamentals"
      contents:
        - fundamentals.qmd

    - id: reference
      title: "Reference"
      contents:
        - reference.qmd
