---
title: "Libraries"
---

When creating interactive documents using Quarto, you can take
advantage of a number of existing components from the JavaScript and
Observable ecosystems.

# The JavaScript libraries ecosystem

### Standard library/npm packages

If you want to use JavaScript modules, many NPM modules are directly
available as [JavaScript
modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)
with the [skypack CDN](https://skypack.dev).

```{ojs}
import { sequential } from 'https://cdn.skypack.dev/@tensorflow/tfjs';
```

# Observablehq.com modules

Here, we highlight some libraries that are particularly useful in
Quarto interactive documents.


## Data manipulation: arquero

[Arquero](https://github.com/uwdata/arquero) is "a JavaScript library
for query processing and transformation of array-backed data tables". If you've used Pandas in Python (or especially dplyr in R), arquero will feel familiar. Here, we import Arquero from its Observable modules

```{ojs}
import { aq, op } from '@uwdata/arquero';
```

## Plotting: vega-lite / Observable plot

```{ojs}
import { vl } from '@vega/vega-lite-api-v5';
```

