---
title: "OJS Cells"
---

OJS code cells `{ojs}` have many options available to control their display and layout. This articles explores these options in depth.

## Cell Output

By default, OJS cells show their full source code and output within rendered documents. Depending on the type of document you are creating you might want to change this behavior either globally or for individual cells.

### Code Visibility

The `echo` option controls whether cells display their source code. To prevent display of code for an entire document, set the `echo: false` option in YAML metadata:

``` yaml
---
title: "My Document"
execute:
  echo: false
---
```

You can also specify this option on a per-cell basis. For example:

```` java
```{{ojs}}
//| echo: false
data = FileAttachment("palmer-penguins.csv").csv()
```
````

### Output Visibility

Above we said that OJS cell output is shown by default. This isn't *exactly* true though. There are two types of output you might see from an OJS cell:

-   Display of inputs, plots, tables, and other content.

-   Display of [Observable inspectors](https://github.com/observablehq/inspector) for variables, datasets, libraries and other intermediate objects.

Inspectors are great when developing a notebook, but they aren't often what you want readers of a long-form article to see. Consequently, Quarto hides inspector output by default (you can cause inspector output to be visible by setting the `output: all` option).

Here's an example to make things more concrete. We'll evaluate the `data` that we read in above and show what this looks like with various `output` settings. By default, you won't see any output at all:

```` java
```{{ojs}}
data = FileAttachment("palmer-penguins.csv").csv()
```
````

```{ojs}
//| echo: false
data = FileAttachment("palmer-penguins.csv").csv()
```

However, if we set the `output: all` option we get a dataset inspector:

```` java
```{{ojs}}
//| output: all
data = FileAttachment("palmer-penguins.csv").csv()
```
````

```{ojs}
//| echo: false
//| output: all
data
```

If you click the inspector you'll see it expand to reveal a subset of the data as JSON. Readers of an article might however prefer to see a scrolling HTML table version of the data, which you can get via the [Inputs.table](https://github.com/observablehq/inputs#Table) function:

```` java
```{{ojs}}
data = FileAttachment("palmer-penguins.csv").csv()
Inputs.table(data)
```
````

```{ojs}
//| echo: false
Inputs.table(data)
```

Note that this output is displayed without any special use of `output: all` (because Quarto knows that the output isn't merely an inspector).

### Code Display

We talked about showing and hiding source code above, but what about controlling exactly how it's displayed?

There are options available for customizing the appearance of code blocks (highlighting, background, border, etc.) as well as how horizontal overflow is handled. See the article on [HTML Code Blocks](../../output-formats/html-code.qmd) for all of the details.

One option we wanted to specifically highlight here is code folding, which enables you to collapse code but still provide an option for users to view it. This is especially handy for custom JavaScript visualizations as they often span dozens of lines of code.

Add the `code-fold: true` option to a code cell to enable code folding (you can also enable this globally). For example:

```` java
```{{ojs}}
//| code-fold: true

```
````

Here's a demonstration (click the "Code" button to show the code):

```{ojs}
//| code-fold: true
pdata = FileAttachment("palmer-penguins.csv").csv({typed: true})

Plot.plot({
  facet: {
    data: pdata,
    x: "sex",
    y: "species",
    marginRight: 80
  },
  marks: [
    Plot.frame(),
    Plot.rectY(pdata, 
      Plot.binX(
        {y: "count"}, 
        {x: "body_mass", thresholds: 20, fill: "species"}
      )
    ),
    Plot.tickX(pdata, 
      Plot.groupZ(
        {x: "median"}, 
        {x: "body_mass",
         z: d => d.sex + d.species,
         stroke: "#333",
         strokeWidth: 2
        }
      )
    )
  ]
})
```

## Cell Layout

There are additional `panel` and `layout` options which you can add to OJS cells to customize how their output is presented. Here's a version of some of the previous examples we've used presented with a sidebar and tabset:

```{ojs}
//| echo: false
filtered = pdata.filter(function(penguin) {
  return bill_length_min < penguin.bill_length &&
         islands.includes(penguin.island);
})
```

```{ojs}
//| echo: false
//| output: true
//| panel: sidebar
viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)
```

::: panel-tabset
## Plot

```{ojs}
//| echo: false
//| output: true
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```

## Data

```{ojs}
//| echo: false
Inputs.table(filtered)
```
:::

We created this layout by first adding the `panel: sidebar` option to the cell with our inputs:

```` java
```{{ojs}}
//| panel: sidebar

viewof bill_length_min = Inputs.range(
  [32, 50], 
  {value: 35, step: 1, label: "Bill length (min):"}
)
viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], 
    label: "Islands:"
  }
)
```
````

We then added a tabset (div of class `.panel-tabset`) with **Plot** and **Data** tabs (headings within the div define the tabs):

```` java
::: {.panel-tabset}

## Plot

```{{ojs}}
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```

## Data

```{{ojs}}
Inputs.table(filtered)
```

:::
````

See the [Layout](examples/layout.qmd) example for the full source code.

Learn more in the article on [Layout](../layout.qmd) for interactive documents.

## Cell Figures

OJS cells can also be rendered as numbered, [cross-referenceable](../../authoring/cross-references.qmd) figures. To do this, add the `label` and `fig-cap` options to the cell. For example:

``` python
```{{ojs}}
//| label: fig-penguin-body-mass
//| fig-cap: "Penguin body mass by sex and species"
```

Then to reference the figure use it's label in a markdown [cross reference](../../authoring/cross-references.qmd):

``` markdown
See @fig-penguin-body-mass for further illustration.
```

Here's how the cross-reference and figure will render:

See @fig-penguin-body-mass for further illustration.

```{ojs}
//| echo: false
//| label: fig-penguin-body-mass
//| fig-cap: "Penguin body mass by sex and species"
Plot.rectY(filtered, 
  Plot.binX(
    {y: "count"}, 
    {x: "body_mass", fill: "species", thresholds: 20}
  ))
  .plot({
    facet: {
      data: filtered,
      x: "sex",
      y: "species",
      marginRight: 80
    },
    marks: [
      Plot.frame(),
    ]
  }
)
```
