---
title: Presentations
format: html
slide-format: revealjs
---

## Overview

Quarto supports a variety of formats for creating presentations, including:

-   `revealjs` --- [reveal.js](revealjs/index.qmd) (HTML)

-   `pptx` --- [PowerPoint](powerpoint.qmd) (MS Office)

-   `beamer` --- [Beamer](beamer.qmd) (LaTeX/PDF)

There are pros and cons to each of these formats. The most capable format by far is `revealjs`, so it is highly recommended unless you have specific Office or LaTeX output requirements. Note that `revealjs` presentations can be presented as HTML slides or can be printed to PDF for easier distribution.

Below, we'll describe the basic syntax for presentations that applies to all formats. See the format-specific articles for additional details on their native capabilities.

{{< include _creating-slides.md >}}

{{< include _incremental-lists.md >}}

{{< include _columns.md >}}


## Learning More

See these format-specific articles for additional details on the additional capabilities of each format:

-   `revealjs` --- [reveal.js](revealjs/index.qmd) (HTML)

-   `pptx` --- [PowerPoint](powerpoint.qmd) (MS Office)

-   `beamer` --- [Beamer](beamer.qmd) (LaTeX/PDF)
