---
title: "Tutorial: Authoring Manuscripts"
---

## Overview

On this page, you'll learn the workflow for authoring manuscripts in Quarto, as well as some of the special Quarto markdown syntax for common elements in articles.

If you haven't already, make sure you've completed the [Tutorial: Set Up](setup.qmd) including [cloning a version of the template repository](setup.qmd#clone-repo).

## Workflow

The basic workflow for writing a manuscript in Quarto is to make changes to your article content in `index.ipynb`, preview the changes with Quarto, and repeat. Let's try it out.

Start by navigating into the manuscript folder and opening Jupyter Lab:
``` {.bash filename="Terminal"}
cd manuscript-tutorial
jupyter lab
```

ADD SCREENSHOT of Jupyterlab open with files pane open showing directory structure.

Open a new Terminal in Jupyter Lab and run:

``` {.bash filename="Terminal"}
quarto preview
```

You'll see some output from Quarto on the Terminal:

``` {.bash filename="Terminal"}
❯ quarto preview
Preparing to preview
[1/2] notebooks/data-screening.ipynb
[2/2] index.ipynb

Creating MECA Archive...
Watching files for changes
Browse at http://localhost:6283/
GET: /
```

And then, a browser window will open with a live preview of the manuscript. You may find it helpful to move and resize your windows so that Jupyter Lab and live preview are side by side.

ADD SCREENSHOT of Jupyterlab with Terminal open, side by side with preview.

The contents of the article is generated by `index.ipynb`. Go ahead and open this file in Jupyter Lab.  You'll dive into the details of this file next, but for now let's make a change and see what happens. 

The first cell (starting with "La Palma Earthquakes") is a Markdown cell, enter Edit mode, and find the line:

``` {.yaml}
title: La Palma Earthquakes
```

Change the line to:

``` {.yaml}
title: La Palma Earthquake Mechanisms
```

Save the notebook, and you'll see the preview update automatically. 

ADD SCREENSHOT that shows side by side: Jupyterlab with first cell in Edit mode and change made; and updated preview

::: {.callout-tip}

If you close the preview accidentally, you can navigate to it again by using the URL from the output in the Terminal, `http://localhost:6283/`. If you want to stop the preview, hit Crtl + C in the Terminal. You can start the preview again by running `quarto preview`.

:::


## The structure of `index.ipynb`

The file `index.ipynb` is a Jupyter Notebook. Like any Jupyter Notebook it contains cells that could be raw, markdown or code. There are two features of this notebook that are Quarto specific:

* The first cell contains a YAML header that is used to set document metadata, including scholarly front matter. This cell must start and end with a line of three dashes (`---`), and within these lines, content is parsed as YAML. You'll notice the cell itself is set to be a Markdown cell, this allows the Quarto Jupyter Lab Extension to visually emulate how some of these options will appear in the rendered document. 

* The other markdown cells use Quarto specific markdown syntax to include things like figures, tables, equations, cross references and citations. 

## Front Matter

The YAML header consists of key-value pairs set using the syntax `key: value`. The header is often extensive for articles because it is used to specify much of the scholarly front matter, like the authors and their affiliations, and the abstract. 

::: {.callout-tip    appearance="simple" collapse="true"}

## Expand to see full YAML header for `index.ipynb`

```yaml
title: La Palma Earthquakes
author:
  - name: Steve Purves
    orcid: 0000-0002-0760-5497
    corresponding: true
    email: steve@curvenote.com
    roles:
      - Investigation
      - Project administration
      - Software
      - Visualization
    affiliations:
      - Curvenote
  - name: Rowan Cockett
    orcid: 0000-0002-7859-8394
    corresponding: false
    roles: []
    affiliations:
      - Curvenote
keywords:
  - La Palma
  - Earthquakes
abstract: |
  In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). ...
plain-language-summary: |
  Earthquake data for the island of La Palma from the September 2021 eruption is found ...
key-points:
  - A web scraping script was developed to pull data from the Instituto Geogràphico Nacional into a machine-readable form for analysis
  - Earthquake events on La Palma are consistent with the presence of both mantle and crustal reservoirs.
date: last-modified
bibliography: references.bib
citation:
  container-title: Earth and Space Science
```

:::

For example, at the top level the header in `index.ipynb` sets the following keys: 
`title`, `author`, `keywords`, `abstract`, `key-points`, `date`, `bibliography`, and `citation`. 

You've seen how editing the `title` key updated the title of the article on the manuscript webpage. The `title` key is also used by the PDF and Word formats, but not all of the keys are used in all formats. For instance, `keywords` is not used in the HTML, PDF or Word formats, but it is used inside the MECA archive. 

You can read more about setting the front matter for your article in [Scholarly Front Matter](docs/authoring/front-matter.qmd).

## Markdown 

Article content written in Markdown cells.  Basic markdown understanding implied: bold, italics, section headings, links.

https://quarto.org/docs/authoring/markdown-basics.html

REST OF PAGE TO WALK THROUGH REMAINING CELLS IN TEMPLATE

## Images/Figures + Captions + Labels 

## Tables + Captions + Labels 

## Cross References 

(Also link to how to add captions and cross references for plots/table that come from computations)

## Equations

## Citations

