---
title: "Next Steps"
---

## Learning More

You've seen the manuscript workflow, and examples of syntax in a complete template.
One way to start your own manuscript is to alter the contents of this template.
Alternatively, you could start from scratch.
Either way, here are some resources to help you with your next steps.

+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### Basics          | Head to [**Manuscript Basics**](/docs/manuscripts/components.html) to:                                                                                                                                                                                                                                                                                         |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   Learn how to turn a directory into a manuscript project by adding the `_quarto.yml` file                                                                                                                                                                                                                                                                   |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   Start a new project with a minimal template using the `quarto create` command                                                                                                                                                                                                                                                                              |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   Controlling manuscript settings in `_quarto.yml`                                                                                                                                                                                                                                                                                                           |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   Add an output format for a specific journal                                                                                                                                                                                                                                                                                                                |
+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### Quarto Projects | Quarto manuscripts are a type of [**Quarto project**](/docs/projects/quarto-projects.html), so anything you can do in a Quarto project applies to a manuscript. For instance, these pages in the Project documentation might be of interest:                                                                                                                   |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   [Managing Execution](/docs/projects/code-execution.html): techniques to avoid expensive computations on every render.                                                                                                                                                                                                                                      |
|                     |                                                                                                                                                                                                                                                                                                                                                                |
|                     | -   [Virtual Environments](/docs/projects/virtual-environments.html): capture your computational environment to facilitate reproducing your work.                                                                                                                                                                                                              |
+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ### Publishing      | We set up the publishing workflow for the template repository, but you can publish your manuscript website any way you can [**publish a Quarto website**](https://quarto.org/docs/publishing/). For example, if you need to set up the workflow to publish to GitHub pages yourself, head to [Publishing to GitHub Pages](/docs/publishing/github-pages.html). |
+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
