---
title: "Script Rendering for knitr"
---

{{< include _pre-release-feature.qmd >}}

## Overview

Quarto v1.4 includes support for rendering R script files (e.g. `.r` or `.R`) that are specially formatted as report. Script rendering is based on `knitr::spin()` feature and makes use of the same [syntax rules](https://bookdown.org/yihui/rmarkdown-cookbook/spin.html), with slight additions: 

- The R script must start with YAML block header inside roxygen comment i.e. using `#'` special comment.
- Cell options can be passed using YAML syntax comment as in `.qmd` i.e. using `#|` special comment.

For example, here is an R script that includes both markdown and code cells:

``` {.r filename="script.R"}
#' ---
#' title: Palmer Penguins
#' author: Norah Jones
#' date: 3/12/23
#' format: html
#' ---

library(palmerpenguins)

#' ## Exploring the data
#' See @fig-bill-sizes for an exploration of bill sizes by species.

#| label: fig-bill-sizes
#| fig-cap: Bill Sizes by Species
#| warning: false
library(ggplot2)
ggplot(data = penguins,
       aes(x = bill_length_mm,
           y = bill_depth_mm,
           group = species)) +
  geom_point(aes(color = species,
                 shape = species),
             size = 3,
             alpha = 0.8) +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Penguin species",
       shape = "Penguin species")

```

Usual `.qmd` content lines starts with `#'`, which includes the YAML header block and any in-document Markdown content. R code is the main content of the R script and included without any delimitation. Cell options are included as normal using `#|` prefixed comments (e.g. `#| echo: false`), and apply to any R code below. Cells are split when Markdown content are inserted in-between R code, e.g. use `#'` to create another block.

## Render and Preview

Rendering and previewing notebook scripts works exactly like `.qmd`. For example, the following commands are all valid:

```bash
$ quarto render script.R

$ quarto preview script.R
```

R scripts rendered with Quarto must begin with a YAML block with lined starting by `#'` (which normally includes the `title` and other YAML options). This convention is how Quarto knows that it should render the `.R` script to output format. The YAML block must follow usual rules and be indented properly.

## Scripts in Projects

R scripts can also be included within [projects](/docs/projects/quarto-projects.qmd) (e.g. websites, blogs, etc.). Scripts within projects are only rendered by Quarto when they start with YAML block header prefixed by `#'` comments.

If for some reason you need to ignore such script, you can create an explict render list in `_quarto.yml` that excludes individual scripts as required, for example:

```yaml
project:
  type: website
  render:
    - "*.{qmd,R}"
    - "!utils.R"
```

Note that this technique is documented for the sake of completeness---in practice you should almost never need to do this since R scripts rarely begin with a YAML block unless you are authoring them specifically for report rendering. 
