---
title: "Advanced Reveal"
---

## Absolute Positioning

## Fragments

-   Fading in/out
-   Colors
-   Animations
-   Sequence

## Slide Transitions

Reveal supports a number of animated transition effects for both slide changes and slide background changes. By default no transitions are used, however you can enable them either globally or per-slide using the options described below.

Here are the available transition types:

| Transition | Description                                                            |
|------------|------------------------------------------------------------------------|
| `none`     | No transition (switch instantly)                                       |
| `fade`     | Cross fade                                                             |
| `slide`    | Slide horizontally                                                     |
| `convex`   | Slide at a convex angle                                                |
| `concave`  | Slide at a concave angle                                               |
| `zoom`     | Scale the incoming slide so it grows in from the center of the screen. |

Here's how you would set the global transition style for both slides and backgrounds:

``` yaml
---
title: "Presentation"
format:
  revealjs:
    transition: slide
    background-transition: fade
---
```

You can also specify the `transition-speed` as `default`, `fast`, or `slow`:

``` yaml
---
title: "Presentation"
format:
  revealjs:
    transition: slide
    transition-speed: fast
---
```

You can also specify the `transition` and/or `transition-speed` for an individual slide:

``` markdown
## Slide Title {transition="fade" transition-speed="fast"}
```

You can also specify separate in and out transitions, for example:

``` markdown
## Slide Title {transition="fade-in slide-out"}
```

## Content Transitions

autoAnimate

-   Slide transitions
-   Background transitions
-   

## Slide Size

-   Options (width, height, margin, minScale, maxScale)

## Content Layout

-   Stacking layout
-   Fitting and stretching content

## Media

-   Preview links
-   Autoplay
-   Iframe preload

## Navigation Options

-   Keyboard
-   Touch
-   Mouse wheel
-   Pausing
-   2d
-   Slide controls
-   Looping
-   Search
-   Invisible Slides

## Plugins

-   Using plugins
