---
title: "Revealjs"
slide-format: revealjs
---

## Overview

You can create [RevealJs](https://revealjs.com/) presentations using the `revealjs` format. Reveal presentations support core presentation features like incremental content, 2-column layouts, and speaker notes, as well as a number of more advanced capabilities including:

-   Image, video, and iframe slide backgrounds.
-   Easy navigation between slides using the slide menu or thumbnail overview mode.
-   A special speaker mode that displays notes, a timer, and the upcoming slide.
-   Printing slides to PDF

``` include
../_creating-slides.md
../_incremental-lists.md
../_incremental-pause.md
../_columns.md
../_speaker-notes.md
```

Press the `s` key (or use the [Slide Menu]) to show the presentation speaker view. You'll typically use this view on one screen (e.g. your laptop) while presenting the slides on another screen.

## Slide Backgrounds

Slides are contained within a limited portion of the screen by default to allow them to fit any display and scale uniformly. You can apply full page backgrounds outside of the slide area by adding a `background` attribute to your slide headers. Four different types of backgrounds are supported: color, image, video and iframe.

### Color Backgrounds

All CSS color formats are supported, including hex values, keywords, `rgba()` or `hsl()`. For example:

``` markdown
## Slide Title {background-color="aquamarine"}
```

### Image Backgrounds

By default, background images are resized to cover the full page. Available options:

| **Attribute**         | **Default** | **Description**                                                                                   |
|:----------------------|:------------|:--------------------------------------------------------------------------------------------------|
| `background-image`    |             | URL of the image to show. GIFs restart when the slide opens.                                      |
| `background-size`     | cover       | See [background-size](https://developer.mozilla.org/docs/Web/CSS/background-size) on MDN.         |
| `background-position` | center      | See [background-position](https://developer.mozilla.org/docs/Web/CSS/background-position) on MDN. |
| `background-repeat`   | no-repeat   | See [background-repeat](https://developer.mozilla.org/docs/Web/CSS/background-repeat) on MDN.     |
| `background-opacity`  | 1           | Opacity of the background image on a 0-1 scale. 0 is transparent and 1 is fully opaque.           |

For example:

``` markdown
## Slide Title {background-image="image.png" background-size="100px" background-repeat="repeat"}

This slide's background image will be sized to 100px and repeated.
```

### Video Backgrounds

Automatically plays a full size video behind the slide.

| **Attribute**            | **Default** | **Description**                                                                         |
|:-------------------------|:------------|:----------------------------------------------------------------------------------------|
| `background-video`       |             | A single video source, or a comma separated list of video sources.                      |
| `background-video-loop`  | false       | Flags if the video should play repeatedly.                                              |
| `background-video-muted` | false       | Flags if the audio should be muted.                                                     |
| `background-size`        | cover       | Use `cover` for full screen and some cropping or `contain` for letterboxing.            |
| `background-opacity`     | 1           | Opacity of the background video on a 0-1 scale. 0 is transparent and 1 is fully opaque. |

For example:

``` markdown
## Slide Title {background-video="video.mp4" background-video-loop="true" background-video-muted="true"}

This slides's background video will play in a loop with audio muted.
```

### IFrame Backgrounds

Embeds a web page as a slide background that covers 100% of the reveal.js width and height. The iframe is in the background layer, behind your slides, and as such it's not possible to interact with it by default. To make your background interactive, you can add the `background-interactive` attribute.

| **Attribute**            | **Default** | **Description**                                                                                                                                 |
|:-------------------------|:------------|:------------------------------------------------------------------------------------------------------------------------------------------------|
| `background-iframe`      |             | URL of the iframe to load                                                                                                                       |
| `background-interactive` | false       | Include this attribute to make it possible to interact with the iframe contents. Enabling this will prevent interaction with the slide content. |

For example:

``` markdown
## Slide Title {background-iframe="https://example.com"}
```

## Slide Menu

Revealjs presentations include a menu in the bottom-left of the slide which provide access to both slide navigation and several presentation tools.

If you prefer to not show the slide menu set the `menu` option to `false`:

``` yaml
---
title: "Presentation"
format:
  revealjs:
    menu: false
---
```

Note that even if the slide menu is hidden you can still activate it by pressing the <kbd>m</kbd> key.
