---
title: "Quarto Reference"
toc-depth: 4
tbl-colwidths: [30, 70]
---

## Code Cells

Cell options affect the execution and output of executable code blocks. Most cell options are available across all engines, however there are some engine-specific options.

|                                    |                                                                                                                                |
|------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|
| [Jupyter](cells/cells-jupyter.qmd) | Jupyter Notebooks combine software code, computational output, explanatory text and multimedia resources in a single document. |
| [Knitr](cells/cells-knitr.qmd)     | Knitr is an R package for dynamic document generation.                                                                         |
| [Observable](cells/cells-ojs.qmd)  | Observable is a set of enhancements to JavaScript tailored for interactive data exploration and analysis.                      |

## Projects

Projects provide a way to render groups of documents at once, sharing options across documents, and for producing aggregate output like websites and books.

|                                  |                                                                                   |
|----------------------------------|-----------------------------------------------------------------------------------|
| [Options](projects/core.qmd)     | Options applicable to all projects.                                               |
| [Website](projects/websites.qmd) | Websites are a convenient way to publish groups of documents.                     |
| [Books](projects/books.qmd)      | Books are combinations of multiple documents (chapters) into a single manuscript. |

## Formats

Output format options control generic output behavior (e.g. numbering, table of contents, etc.) as well as various format specific capabilities.

#### Documents

|                               |                                                                                   |
|-------------------------------|-----------------------------------------------------------------------------------|
| [HTML](formats/html.qmd)      | HTML is a markup language used for structuring and presenting content on the web. |
| [PDF](formats/pdf.qmd)        | PDF is a file format for creating print-ready paged documents.                    |
| [MS Word](formats/docx.qmd)   | MS Word is the word processor included with Microsoft Office.                     |
| [OpenOffice](formats/odt.qmd) | OpenDocument is an open standard file format for word processing documents.       |
| [ePub](formats/epub.qmd)      | ePub is an e-book file format that is supported by many e-readers.                |

#### Presentations

|                                                |                                                                                 |
|------------------------------------------------|---------------------------------------------------------------------------------|
| [Revealjs](formats/presentations/revealjs.qmd) | Revealjs is an open source HTML presentation framework.                         |
| [PowerPoint](formats/presentations/pptx.qmd)   | PowerPoint is the presentation editing software included with Microsoft Office. |
| [Beamer](formats/presentations/beamer.qmd)     | Beamer is a LaTeX class for producing presentations and slides.                 |

#### Markdown

|                                               |                                                                                                                   |
|-----------------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| [GitHub](formats/markdown/gfm.qmd)            | GitHub Flavored Markdown (GFM) is the dialect of Markdown that is currently supported for user content on GitHub. |
| [CommonMark](formats/markdown/commonmark.qmd) | CommonMark is a strongly defined, highly compatible specification of Markdown.                                    |
| [Hugo](formats/markdown/hugo.qmd)             | Hugo is an open-source static website generator.                                                                  |
| [Markua](formats/markdown/markua.qmd)         | Markua is a markdown variant used by Leanpub.                                                                     |

#### WIkis

|                                         |                                                                                                                   |
|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| [MediaWiki](formats/wiki/mediawiki.qmd) | MediaWiki is the native document format of Wikipedia.                                                             |
| [DokuWiki](formats/wiki/dokuwiki.qmd)   | DokuWiki is a simple to use and highly versatile open source wiki software that doesn't require a database.       |
| [ZimWiki](formats/wiki/zimwiki.qmd)     | Zim is a graphical text editor used to maintain a collection of wiki pages.                                       |
| [Jira Wiki](formats/wiki/jira.qmd)      | Jira Wiki is the native document format for the Jira issue tracking and project management system from Atlassian. |

#### More Formats

|                                       |                                                                                                                                                                                                |
|---------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [JATS](formats/jats.qmd)              | JATS (Journal Article Tag Suite) is an XML format for marking up and exchanging journal content                                                                                                |
| [Jupyter](formats/ipynb.qmd)          | Jupyter Notebooks combine software code, computational output, explanatory text and multimedia resources in a single document.                                                                 |
| [ConTeXt](formats/context.qmd)        | Context is a system for typesetting documents based on TEX and METAPOST.                                                                                                                       |
| [RTF](formats/rtf.qmd)                | The Rich Text Format (RTF) is a file format for for cross-platform document interchange.                                                                                                       |
| [reST](formats/rst.qmd)               | reStructuredText is an easy-to-read, what-you-see-is-what-you-get plaintext markup syntax and parser system.                                                                                   |
| [AsciiDoc](formats/asciidoc.qmd)      | AsciiDoc is a text document format for writing documentation, articles, and books, ebooks, slideshows, web pages, man pages and blogs.                                                         |
| [Org-Mode](formats/org.qmd)           | Org-Mode is an Emacs major mode for keeping notes, authoring documents, creating computational notebooks, and more.                                                                            |
| [Muse](formats/muse.qmd)              | Emacs Muse is an authoring and publishing environment for Emacs.                                                                                                                               |
| [GNU Texinfo](formats/texinfo.qmd)    | Texinfo is the official documentation format of the GNU project.                                                                                                                               |
| [Groff Man Page](formats/man.qmd)     | The Groff (GNU troff) man page document formats consists of plain text mixed with formatting commands that produce ASCII/UTF8 for display at the terminal                                      |
| [Groff Manuscript](formats/ms.qmd)    | The Groff (GNU troff) manuscript format consists of plain text mixed with formatting commands that produces PostScript, PDF, or HTML                                                           |
| [Haddock markup](formats/haddock.qmd) | Haddock is a tool for automatically generating documentation from annotated Haskell source code                                                                                                |
| [OPML](formats/opml.qmd)              | OPML (Outline Processor Markup Language) is an XML format for outlines.                                                                                                                        |
| [Textile](formats/textile.qmd)        | Textile is a simple text markup language that makes it easy to structure content for blogs, wikis, and documentation.                                                                          |
| [DocBook](formats/docbook.qmd)        | DocBook is an XML schema particularly well suited to books and papers about computer hardware and software.                                                                                    |
| [InDesign](formats/icml.qmd)          | ICML is an XML representation of an Adobe InDesign document.                                                                                                                                   |
| [TEI Simple](formats/tei.qmd)         | TEI Simple aims to define a new *highly-constrained* and *prescriptive* subset of the Text Encoding Initiative (TEI) Guidelines suited to the representation of early modern and modern books. |
| [FictionBook](formats/fb2.qmd)        | FictionBook is an open XML-based e-book format.                                                                                                                                                |
