---
title: "Dashboards Tutorial"
---

{{< include /docs/prerelease/1.4/_pre-release-feature.qmd >}}


## Overview

In this tutorial we'll provide a broad overview of the core concepts and capabilities of dashboards, including:

- How to incorporate plots and tables into dashboards.

- How to create dashboards with multiple pages, tabsets, and flexible row and column based layouts.

- How to add value boxes and text annotations to make dashboards more engaging.

- How to make dashboards interactive using Shiny. 


We'll assume you know the basics of how to render and preview Quarto documents. If you are completely new to Quarto, you may first want to familiarze yourself with the Qurato tools available for your favorite development environment. See the documentation on using Quarto with [VS Code](/docs/tools/vscode.qmd), [JupyterLab](/docs/tools/jupyter-lab.qmd), [RStudio](/docs/tools/rstudio.qmd), [Neovim](/docs/tools/neovim.qmd), or [other text editors](/docs/tools/text-editors.qmd) for more details.


## Learning More

{{< include _learning-more.md >}}


