project:
  type: site
  output-dir: docs

site:
  title: "Quarto Demo"
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit]
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: bluesky
        href: https://bsky.app/profile/quarto.org
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/quarto-dev/quarto-demo
          - text: Report a Bug
            href: https://github.com/quarto-dev/quarto-demo/issues/new
    contents:
      - section: "Basics"
        contents:
          - index.md
          - basics-knitr.Rmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.md
          - layout-knitr.Rmd
          - layout-jupyter.qmd
      - section: "Crossrefs"
        contents:
          - crossref.md
          - crossref-knitr.Rmd
          - crossref-jupyter.qmd
      - section: "HTML"
        contents:
          - html-basics.Rmd
          - html-bootstrap.Rmd
          - html-themes.md
      - section: "Websites"
        contents:
          - website-basics.md
          - website-navigation.md
      - section: "Books"
        contents:
          - book-basics.md
          - book-authoring.md

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: darkly
    

