# Uploads index to our Algolia Index
name: Upload Index
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  upload-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install Algolia API Dependencies
        run: |
          gem install algolia -v 2.3.4
      - name: Upload Index for release website
        run: |
          pwd
          ruby .github/workflows/upload-algolia.rb
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ZPJB5I1QN7
          ALGOLIA_INDEX: prod_QUARTO
          QUARTO_INDEX_PATH: search.json
          QUARTO_INDEX_URL: https://quarto.org/search.json
      - name: Upload Index for pre-release website
        run: |
          pwd
          ruby .github/workflows/upload-algolia.rb
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ZPJB5I1QN7
          ALGOLIA_INDEX: prerelease_QUARTO
          QUARTO_INDEX_PATH: search.json
          QUARTO_INDEX_URL: https://prerelease.quarto.org/search.json
          
          
