---
title: Include Quarto Markdown in LaTeX Raw Blocks
summary: Allows library authors to emit raw blocks that include Quarto features like cross-references or shortcodes.
---

Use the syntax `\QuartoMarkdownBase64{<<base64-encoded-markdown-content>>}` 
to include Quarto Markdown in LaTeX raw blocks. 
When this syntax is detected by Quarto, the contents will be decoded, 
processed in Quarto (including user filters), and then inserted back into the LaTeX raw block.
This allows libraries that emit raw blocks to benefit
from Quarto features such as cross-reference resolution and shortcodes.

This is useful for third-party libraries that seek to emit LaTeX content that nevertheless 
can have "quarto content". Note that, unlike the [equivalent HTML feature](/docs/authoring/tables.qmd#html-tables), 
Quarto currently only supports base-64 encoded content in LaTeX blocks.

This LaTeX feature cannot currently be disabled.
We expect this to not be necessary because `QuartoMarkdownBase64` is unlikely to conflict with
existing LaTeX environments.